[package]
name = "aurelia"
version = "0.1.0"
description = "A music player for Jellyfin"
authors = ["pupbrained"]
edition = "2024"

[lib]
name = "aurelia_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
openapiv3 = "2.2.0"
prettyplease = "0.2.37"
progenitor = "0.11.2"
serde_json = "1"
syn = { version = "2.0", features = ["full"] }
tauri-build = { version = "2", features = [] }
toml_edit = "0.23"

[dependencies]
anyhow = "1.0"
base64 = "0.22"
biquad = "0.5.0"
chrono = { version = "0.4.38", features = ["serde"] }
derive_more = { version = "2.1", features = ["display"] }
dirs = "6.0"
discord-rich-presence = "1"
md5 = "0.8"
once_cell = "1.21.3"
postcard = { version = "1.0", features = ["use-std"] }
progenitor-client = "0.11.2"
rand = "0.9.2"
redb = "3.1.0"
reqwest = { version = "0.12", default-features = false, features = [
  "blocking",
  "json",
  "rustls-tls",
  "stream",
] }
rodio = { version = "0.21.1", default-features = false, features = [
  "playback",
  "symphonia-all",
] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
specta = "=2.0.0-rc.22"
specta-typescript = "=0.0.9"
stream-download = { version = "0.22.9", features = ["reqwest-rustls"] }
tauri = { version = "2", features = [
  "protocol-asset",
  "macos-private-api",
  "devtools",
  "tray-icon",
] }
tauri-plugin-clipboard-manager = "2.3.0"
tauri-plugin-fs = "2"
tauri-plugin-m3 = "0.2"
tauri-plugin-opener = "2"
tauri-plugin-os = "2"
tauri-plugin-store = "2"
tauri-specta = { version = "=2.0.0-rc.21", features = ["derive", "typescript"] }
thiserror = "2.0"
tokio = { version = "1", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
urlencoding = "2.1.3"
uuid = { version = "1.19", features = ["v4"] }
window-vibrancy = "0.7"
