export interface AccentColor {
  displayName: string
  foreground?: string
  hex:         string
  name:        string
}

export interface ColorScheme {
  accentColors: AccentColor[]
  colors: {
    accent:                string
    accentForeground:      string
    background:            string
    backgroundDark:        string
    border:                string
    card:                  string
    cardForeground:        string
    destructive:           string
    destructiveForeground: string
    foreground:            string
    input:                 string
    muted:                 string
    mutedForeground:       string
    popover:               string
    popoverForeground:     string
    primary:               string
    primaryForeground:     string
    ring:                  string
    secondary:             string
    secondaryForeground:   string
    sidebar:               string
    success:               string
  }
  displayName: string
  name:        string
}

export const COLOR_SCHEMES: ColorScheme[] = [
  {
    accentColors: [
      { displayName: 'Red', hex: '#ef4444', name: 'red' },
      { displayName: 'Orange', hex: '#f97316', name: 'orange' },
      { displayName: 'Yellow', hex: '#f59e0b', name: 'yellow' },
      { displayName: 'Green', hex: '#10b981', name: 'green' },
      { displayName: 'Blue', hex: '#3b82f6', name: 'blue' },
      { displayName: 'Purple', hex: '#8b5cf6', name: 'purple' },
      { displayName: 'Pink', hex: '#ec4899', name: 'pink' },
    ],
    colors: {
      accent:                '#64748b',
      accentForeground:      'oklch(0.985 0 0)',
      background:            'oklch(1 0 0)',
      backgroundDark:        'oklch(0.98 0 0)',
      border:                'oklch(0.92 0.004 286.32)',
      card:                  'oklch(1 0 0)',
      cardForeground:        'oklch(0.141 0.005 285.823)',
      destructive:           'oklch(0.577 0.245 27.325)',
      destructiveForeground: 'oklch(0.985 0 0)',
      foreground:            'oklch(0.141 0.005 285.823)',
      input:                 'oklch(0.92 0.004 286.32)',
      muted:                 'oklch(0.967 0.001 286.375)',
      mutedForeground:       'oklch(0.552 0.016 285.938)',
      popover:               'oklch(1 0 0)',
      popoverForeground:     'oklch(0.141 0.005 285.823)',
      primary:               'oklch(0.21 0.006 285.885)',
      primaryForeground:     'oklch(0.985 0 0)',
      ring:                  'oklch(0.705 0.015 286.067)',
      secondary:             'oklch(0.967 0.001 286.375)',
      secondaryForeground:   'oklch(0.21 0.006 285.885)',
      sidebar:               'oklch(0.85 0.01 286.375)',
      success:               '#10b981',
    },
    displayName: 'Default Light',
    name:        'default-light',
  },
  {
    accentColors: [
      { displayName: 'Red', foreground: 'oklch(0.21 0.006 285.885)', hex: '#ef4444', name: 'red' },
      { displayName: 'Orange', foreground: 'oklch(0.21 0.006 285.885)', hex: '#f97316', name: 'orange' },
      { displayName: 'Yellow', foreground: 'oklch(0.21 0.006 285.885)', hex: '#f59e0b', name: 'yellow' },
      { displayName: 'Green', foreground: 'oklch(0.21 0.006 285.885)', hex: '#10b981', name: 'green' },
      { displayName: 'Blue', foreground: 'oklch(0.21 0.006 285.885)', hex: '#3b82f6', name: 'blue' },
      { displayName: 'Purple', foreground: 'oklch(0.21 0.006 285.885)', hex: '#8b5cf6', name: 'purple' },
      { displayName: 'Pink', foreground: 'oklch(0.21 0.006 285.885)', hex: '#ec4899', name: 'pink' },
    ],
    colors: {
      accent:                '#64748b',
      accentForeground:      'oklch(0.985 0 0)',
      background:            'oklch(0.141 0.005 285.823)',
      backgroundDark:        'oklch(0.1 0.005 285.823)',
      border:                'oklch(0.274 0.006 286.033)',
      card:                  'oklch(0.141 0.005 285.823)',
      cardForeground:        'oklch(0.985 0 0)',
      destructive:           '#ef4444',
      destructiveForeground: 'oklch(0.141 0.005 285.823)',
      foreground:            'oklch(0.985 0 0)',
      input:                 'oklch(0.274 0.006 286.033)',
      muted:                 'oklch(0.274 0.006 286.033)',
      mutedForeground:       'oklch(0.705 0.015 286.067)',
      popover:               'oklch(0.141 0.005 285.823)',
      popoverForeground:     'oklch(0.985 0 0)',
      primary:               'oklch(0.985 0 0)',
      primaryForeground:     'oklch(0.21 0.006 285.885)',
      ring:                  'oklch(0.442 0.017 285.786)',
      secondary:             'oklch(0.274 0.006 286.033)',
      secondaryForeground:   'oklch(0.985 0 0)',
      sidebar:               '#000000',
      success:               '#10b981',
    },
    displayName: 'Default Dark',
    name:        'default-dark',
  },
  {
    accentColors: [
      { displayName: 'Red', hex: '#d20f39', name: 'red' },
      { displayName: 'Orange', hex: '#fe640b', name: 'orange' },
      { displayName: 'Yellow', hex: '#df8e1d', name: 'yellow' },
      { displayName: 'Green', hex: '#40a02b', name: 'green' },
      { displayName: 'Blue', hex: '#1e66f5', name: 'blue' },
      { displayName: 'Purple', hex: '#8839ef', name: 'purple' },
      { displayName: 'Pink', hex: '#ea76cb', name: 'pink' },
    ],
    colors: {
      accent:                '#dc8a78',
      accentForeground:      '#eff1f5',
      background:            '#eff1f5',
      backgroundDark:        '#e6e9ef',
      border:                '#9ca0b0',
      card:                  '#eff1f5',
      cardForeground:        '#4c4f69',
      destructive:           '#d20f39',
      destructiveForeground: '#eff1f5',
      foreground:            '#4c4f69',
      input:                 '#9ca0b0',
      muted:                 '#bcc0cc',
      mutedForeground:       '#6c6f85',
      popover:               '#eff1f5',
      popoverForeground:     '#4c4f69',
      primary:               '#1e66f5',
      primaryForeground:     '#eff1f5',
      ring:                  '#1e66f5',
      secondary:             '#acb0be',
      secondaryForeground:   '#4c4f69',
      sidebar:               '#d1d5db',
      success:               '#40a02b',
    },
    displayName: 'Catppuccin Latte',
    name:        'catppuccin-latte',
  },
  {
    accentColors: [
      { displayName: 'Red', hex: '#e78284', name: 'red' },
      { displayName: 'Orange', hex: '#f2a66f', name: 'orange' },
      { displayName: 'Yellow', hex: '#e5c890', name: 'yellow' },
      { displayName: 'Green', hex: '#a6d189', name: 'green' },
      { displayName: 'Blue', hex: '#8caaee', name: 'blue' },
      { displayName: 'Purple', hex: '#ca9ee6', name: 'purple' },
      { displayName: 'Pink', hex: '#f4b8e4', name: 'pink' },
    ],
    colors: {
      accent:                '#f2d5cf',
      accentForeground:      '#303446',
      background:            '#303446',
      backgroundDark:        '#1a1a2e',
      border:                '#626880',
      card:                  '#303446',
      cardForeground:        '#c6d0f5',
      destructive:           '#e78284',
      destructiveForeground: '#303446',
      foreground:            '#c6d0f5',
      input:                 '#626880',
      muted:                 '#737994',
      mutedForeground:       '#949cbb',
      popover:               '#303446',
      popoverForeground:     '#c6d0f5',
      primary:               '#8caaee',
      primaryForeground:     '#303446',
      ring:                  '#8caaee',
      secondary:             '#626880',
      secondaryForeground:   '#c6d0f5',
      sidebar:               '#292c3c',
      success:               '#a6d189',
    },
    displayName: 'Catppuccin Frappé',
    name:        'catppuccin-frappe',
  },
  {
    accentColors: [
      { displayName: 'Red', hex: '#ed8796', name: 'red' },
      { displayName: 'Orange', hex: '#f5a97f', name: 'orange' },
      { displayName: 'Yellow', hex: '#eed49f', name: 'yellow' },
      { displayName: 'Green', hex: '#a6da95', name: 'green' },
      { displayName: 'Blue', hex: '#8aadf4', name: 'blue' },
      { displayName: 'Purple', hex: '#c6a0f6', name: 'purple' },
      { displayName: 'Pink', hex: '#f5bde6', name: 'pink' },
    ],
    colors: {
      accent:                '#f4dbd6',
      accentForeground:      '#24273a',
      background:            '#24273a',
      backgroundDark:        '#1a1a2e',
      border:                '#5b6078',
      card:                  '#24273a',
      cardForeground:        '#cad3f5',
      destructive:           '#ed8796',
      destructiveForeground: '#24273a',
      foreground:            '#cad3f5',
      input:                 '#5b6078',
      muted:                 '#6e738d',
      mutedForeground:       '#a5adcb',
      popover:               '#24273a',
      popoverForeground:     '#cad3f5',
      primary:               '#8aadf4',
      primaryForeground:     '#24273a',
      ring:                  '#8aadf4',
      secondary:             '#5b6078',
      secondaryForeground:   '#cad3f5',
      sidebar:               '#1e1e2e',
      success:               '#a6da95',
    },
    displayName: 'Catppuccin Macchiato',
    name:        'catppuccin-macchiato',
  },
  {
    accentColors: [
      { displayName: 'Red', hex: '#f38ba8', name: 'red' },
      { displayName: 'Orange', hex: '#fab387', name: 'orange' },
      { displayName: 'Yellow', hex: '#f9e2af', name: 'yellow' },
      { displayName: 'Green', hex: '#a6e3a1', name: 'green' },
      { displayName: 'Blue', hex: '#89b4fa', name: 'blue' },
      { displayName: 'Purple', hex: '#cba6f7', name: 'purple' },
      { displayName: 'Pink', hex: '#f5c2e7', name: 'pink' },
    ],
    colors: {
      accent:                '#f5e0dc',
      accentForeground:      '#1e1e2e',
      background:            '#1e1e2e',
      backgroundDark:        '#11111b',
      border:                '#585b70',
      card:                  '#1e1e2e',
      cardForeground:        '#cdd6f4',
      destructive:           '#f38ba8',
      destructiveForeground: '#1e1e2e',
      foreground:            '#cdd6f4',
      input:                 '#585b70',
      muted:                 '#6c7086',
      mutedForeground:       '#a6adc8',
      popover:               '#1e1e2e',
      popoverForeground:     '#cdd6f4',
      primary:               '#89b4fa',
      primaryForeground:     '#1e1e2e',
      ring:                  '#89b4fa',
      secondary:             '#585b70',
      secondaryForeground:   '#cdd6f4',
      sidebar:               '#181825',
      success:               '#a6e3a1',
    },
    displayName: 'Catppuccin Mocha',
    name:        'catppuccin-mocha',
  },
  {
    accentColors: [
      { displayName: 'Red', hex: '#cc241d', name: 'red' },
      { displayName: 'Orange', hex: '#d65d0e', name: 'orange' },
      { displayName: 'Yellow', hex: '#d79921', name: 'yellow' },
      { displayName: 'Green', hex: '#98971a', name: 'green' },
      { displayName: 'Blue', hex: '#458588', name: 'blue' },
      { displayName: 'Purple', hex: '#b16286', name: 'purple' },
      { displayName: 'Pink', hex: '#d3869b', name: 'pink' },
    ],
    colors: {
      accent:                '#d79921',
      accentForeground:      '#fbf1c7',
      background:            '#fbf1c7',
      backgroundDark:        '#f2e6b6',
      border:                '#bdae93',
      card:                  '#fbf1c7',
      cardForeground:        '#3c3836',
      destructive:           '#cc241d',
      destructiveForeground: '#fbf1c7',
      foreground:            '#3c3836',
      input:                 '#bdae93',
      muted:                 '#d5c4a1',
      mutedForeground:       '#665c54',
      popover:               '#fbf1c7',
      popoverForeground:     '#3c3836',
      primary:               '#458588',
      primaryForeground:     '#fbf1c7',
      ring:                  '#458588',
      secondary:             '#ebdbb2',
      secondaryForeground:   '#3c3836',
      sidebar:               '#d5c4a1',
      success:               '#98971a',
    },
    displayName: 'Gruvbox Light',
    name:        'gruvbox-light',
  },
  {
    accentColors: [
      { displayName: 'Red', foreground: '#282828', hex: '#fb4934', name: 'red' },
      { displayName: 'Orange', foreground: '#282828', hex: '#fe8019', name: 'orange' },
      { displayName: 'Yellow', foreground: '#282828', hex: '#fabd2f', name: 'yellow' },
      { displayName: 'Green', foreground: '#282828', hex: '#b8bb26', name: 'green' },
      { displayName: 'Blue', foreground: '#282828', hex: '#83a598', name: 'blue' },
      { displayName: 'Purple', foreground: '#282828', hex: '#d3869b', name: 'purple' },
      { displayName: 'Pink', foreground: '#282828', hex: '#d3869b', name: 'pink' },
    ],
    colors: {
      accent:                '#fabd2f',
      accentForeground:      '#282828',
      background:            '#282828',
      backgroundDark:        '#1a1a1a',
      border:                '#504945',
      card:                  '#282828',
      cardForeground:        '#ebdbb2',
      destructive:           '#fb4934',
      destructiveForeground: '#282828',
      foreground:            '#ebdbb2',
      input:                 '#504945',
      muted:                 '#665c54',
      mutedForeground:       '#a89984',
      popover:               '#282828',
      popoverForeground:     '#ebdbb2',
      primary:               '#83a598',
      primaryForeground:     '#282828',
      ring:                  '#83a598',
      secondary:             '#504945',
      secondaryForeground:   '#ebdbb2',
      sidebar:               '#1d2021',
      success:               '#b8bb26',
    },
    displayName: 'Gruvbox Dark',
    name:        'gruvbox-dark',
  },
]
