export interface AccentColor {
  name:        string
  displayName: string
  hex:         string
  foreground?: string
}

export interface ColorScheme {
  name:         string
  displayName:  string
  accentColors: AccentColor[]
  colors: {
    background:            string
    foreground:            string
    card:                  string
    cardForeground:        string
    popover:               string
    popoverForeground:     string
    primary:               string
    primaryForeground:     string
    secondary:             string
    secondaryForeground:   string
    muted:                 string
    mutedForeground:       string
    accent:                string
    accentForeground:      string
    destructive:           string
    destructiveForeground: string
    border:                string
    input:                 string
    ring:                  string
    chart1:                string
    chart2:                string
    chart3:                string
    chart4:                string
    chart5:                string
    sidebar:               string
  }
}

export const COLOR_SCHEMES: ColorScheme[] = [
  {
    name:         'default-light',
    displayName:  'Default Light',
    accentColors: [
      { name: 'red', displayName: 'Red', hex: '#ef4444' },
      { name: 'orange', displayName: 'Orange', hex: '#f97316' },
      { name: 'yellow', displayName: 'Yellow', hex: '#f59e0b' },
      { name: 'green', displayName: 'Green', hex: '#10b981' },
      { name: 'blue', displayName: 'Blue', hex: '#3b82f6' },
      { name: 'purple', displayName: 'Purple', hex: '#8b5cf6' },
      { name: 'pink', displayName: 'Pink', hex: '#ec4899' },
    ],
    colors: {
      background:            'oklch(1 0 0)',
      foreground:            'oklch(0.141 0.005 285.823)',
      card:                  'oklch(1 0 0)',
      cardForeground:        'oklch(0.141 0.005 285.823)',
      popover:               'oklch(1 0 0)',
      popoverForeground:     'oklch(0.141 0.005 285.823)',
      primary:               'oklch(0.21 0.006 285.885)',
      primaryForeground:     'oklch(0.985 0 0)',
      secondary:             'oklch(0.967 0.001 286.375)',
      secondaryForeground:   'oklch(0.21 0.006 285.885)',
      muted:                 'oklch(0.967 0.001 286.375)',
      mutedForeground:       'oklch(0.552 0.016 285.938)',
      accent:                '#64748b',
      accentForeground:      'oklch(0.985 0 0)',
      destructive:           'oklch(0.577 0.245 27.325)',
      destructiveForeground: 'oklch(0.577 0.245 27.325)',
      border:                'oklch(0.92 0.004 286.32)',
      input:                 'oklch(0.92 0.004 286.32)',
      ring:                  'oklch(0.705 0.015 286.067)',
      chart1:                'oklch(0.646 0.222 41.116)',
      chart2:                'oklch(0.6 0.118 184.704)',
      chart3:                'oklch(0.398 0.07 227.392)',
      chart4:                'oklch(0.828 0.189 84.429)',
      chart5:                'oklch(0.769 0.188 70.08)',
      sidebar:               'oklch(0.85 0.01 286.375)',
    },
  },
  {
    name:         'default-dark',
    displayName:  'Default Dark',
    accentColors: [
      { name: 'red', displayName: 'Red', hex: '#ef4444', foreground: 'oklch(0.21 0.006 285.885)' },
      { name: 'orange', displayName: 'Orange', hex: '#f97316', foreground: 'oklch(0.21 0.006 285.885)' },
      { name: 'yellow', displayName: 'Yellow', hex: '#f59e0b', foreground: 'oklch(0.21 0.006 285.885)' },
      { name: 'green', displayName: 'Green', hex: '#10b981', foreground: 'oklch(0.21 0.006 285.885)' },
      { name: 'blue', displayName: 'Blue', hex: '#3b82f6', foreground: 'oklch(0.21 0.006 285.885)' },
      { name: 'purple', displayName: 'Purple', hex: '#8b5cf6', foreground: 'oklch(0.21 0.006 285.885)' },
      { name: 'pink', displayName: 'Pink', hex: '#ec4899', foreground: 'oklch(0.21 0.006 285.885)' },
    ],
    colors: {
      background:            'oklch(0.141 0.005 285.823)',
      foreground:            'oklch(0.985 0 0)',
      card:                  'oklch(0.141 0.005 285.823)',
      cardForeground:        'oklch(0.985 0 0)',
      popover:               'oklch(0.141 0.005 285.823)',
      popoverForeground:     'oklch(0.985 0 0)',
      primary:               'oklch(0.985 0 0)',
      primaryForeground:     'oklch(0.21 0.006 285.885)',
      secondary:             'oklch(0.274 0.006 286.033)',
      secondaryForeground:   'oklch(0.985 0 0)',
      muted:                 'oklch(0.274 0.006 286.033)',
      mutedForeground:       'oklch(0.705 0.015 286.067)',
      accent:                '#64748b',
      accentForeground:      'oklch(0.985 0 0)',
      destructive:           'oklch(0.396 0.141 25.723)',
      destructiveForeground: 'oklch(0.637 0.237 25.331)',
      border:                'oklch(0.274 0.006 286.033)',
      input:                 'oklch(0.274 0.006 286.033)',
      ring:                  'oklch(0.442 0.017 285.786)',
      chart1:                'oklch(0.488 0.243 264.376)',
      chart2:                'oklch(0.696 0.17 162.48)',
      chart3:                'oklch(0.769 0.188 70.08)',
      chart4:                'oklch(0.627 0.265 303.9)',
      chart5:                'oklch(0.645 0.246 16.439)',
      sidebar:               '#000000',
    },
  },
  {
    name:         'catppuccin-latte',
    displayName:  'Catppuccin Latte',
    accentColors: [
      { name: 'red', displayName: 'Red', hex: '#d20f39' },
      { name: 'orange', displayName: 'Orange', hex: '#fe640b' },
      { name: 'yellow', displayName: 'Yellow', hex: '#df8e1d' },
      { name: 'green', displayName: 'Green', hex: '#40a02b' },
      { name: 'blue', displayName: 'Blue', hex: '#1e66f5' },
      { name: 'purple', displayName: 'Purple', hex: '#8839ef' },
      { name: 'pink', displayName: 'Pink', hex: '#ea76cb' },
    ],
    colors: {
      background:            '#eff1f5',
      foreground:            '#4c4f69',
      card:                  '#eff1f5',
      cardForeground:        '#4c4f69',
      popover:               '#eff1f5',
      popoverForeground:     '#4c4f69',
      primary:               '#1e66f5',
      primaryForeground:     '#eff1f5',
      secondary:             '#acb0be',
      secondaryForeground:   '#4c4f69',
      muted:                 '#bcc0cc',
      mutedForeground:       '#6c6f85',
      accent:                '#dc8a78',
      accentForeground:      '#eff1f5',
      destructive:           '#d20f39',
      destructiveForeground: '#eff1f5',
      border:                '#9ca0b0',
      input:                 '#9ca0b0',
      ring:                  '#1e66f5',
      chart1:                '#1e66f5',
      chart2:                '#dc8a78',
      chart3:                '#40a02b',
      chart4:                '#df8e1d',
      chart5:                '#ea76cb',
      sidebar:               '#d1d5db',
    },
  },
  {
    name:         'catppuccin-frappe',
    displayName:  'Catppuccin Frappé',
    accentColors: [
      { name: 'red', displayName: 'Red', hex: '#e78284' },
      { name: 'orange', displayName: 'Orange', hex: '#f2a66f' },
      { name: 'yellow', displayName: 'Yellow', hex: '#e5c890' },
      { name: 'green', displayName: 'Green', hex: '#a6d189' },
      { name: 'blue', displayName: 'Blue', hex: '#8caaee' },
      { name: 'purple', displayName: 'Purple', hex: '#ca9ee6' },
      { name: 'pink', displayName: 'Pink', hex: '#f4b8e4' },
    ],
    colors: {
      background:            '#303446',
      foreground:            '#c6d0f5',
      card:                  '#303446',
      cardForeground:        '#c6d0f5',
      popover:               '#303446',
      popoverForeground:     '#c6d0f5',
      primary:               '#8caaee',
      primaryForeground:     '#303446',
      secondary:             '#626880',
      secondaryForeground:   '#c6d0f5',
      muted:                 '#737994',
      mutedForeground:       '#949cbb',
      accent:                '#f2d5cf',
      accentForeground:      '#303446',
      destructive:           '#e78284',
      destructiveForeground: '#303446',
      border:                '#626880',
      input:                 '#626880',
      ring:                  '#8caaee',
      chart1:                '#8caaee',
      chart2:                '#f2d5cf',
      chart3:                '#a6d189',
      chart4:                '#e5c890',
      chart5:                '#f4b8e4',
      sidebar:               '#292c3c',
    },
  },
  {
    name:         'catppuccin-macchiato',
    displayName:  'Catppuccin Macchiato',
    accentColors: [
      { name: 'red', displayName: 'Red', hex: '#ed8796' },
      { name: 'orange', displayName: 'Orange', hex: '#f5a97f' },
      { name: 'yellow', displayName: 'Yellow', hex: '#eed49f' },
      { name: 'green', displayName: 'Green', hex: '#a6da95' },
      { name: 'blue', displayName: 'Blue', hex: '#8aadf4' },
      { name: 'purple', displayName: 'Purple', hex: '#c6a0f6' },
      { name: 'pink', displayName: 'Pink', hex: '#f5bde6' },
    ],
    colors: {
      background:            '#24273a',
      foreground:            '#cad3f5',
      card:                  '#24273a',
      cardForeground:        '#cad3f5',
      popover:               '#24273a',
      popoverForeground:     '#cad3f5',
      primary:               '#8aadf4',
      primaryForeground:     '#24273a',
      secondary:             '#5b6078',
      secondaryForeground:   '#cad3f5',
      muted:                 '#6e738d',
      mutedForeground:       '#a5adcb',
      accent:                '#f4dbd6',
      accentForeground:      '#24273a',
      destructive:           '#ed8796',
      destructiveForeground: '#24273a',
      border:                '#5b6078',
      input:                 '#5b6078',
      ring:                  '#8aadf4',
      chart1:                '#8aadf4',
      chart2:                '#f4dbd6',
      chart3:                '#a6da95',
      chart4:                '#eed49f',
      chart5:                '#f5bde6',
      sidebar:               '#1e1e2e',
    },
  },
  {
    name:         'catppuccin-mocha',
    displayName:  'Catppuccin Mocha',
    accentColors: [
      { name: 'red', displayName: 'Red', hex: '#f38ba8' },
      { name: 'orange', displayName: 'Orange', hex: '#fab387' },
      { name: 'yellow', displayName: 'Yellow', hex: '#f9e2af' },
      { name: 'green', displayName: 'Green', hex: '#a6e3a1' },
      { name: 'blue', displayName: 'Blue', hex: '#89b4fa' },
      { name: 'purple', displayName: 'Purple', hex: '#cba6f7' },
      { name: 'pink', displayName: 'Pink', hex: '#f5c2e7' },
    ],
    colors: {
      background:            '#1e1e2e',
      foreground:            '#cdd6f4',
      card:                  '#1e1e2e',
      cardForeground:        '#cdd6f4',
      popover:               '#1e1e2e',
      popoverForeground:     '#cdd6f4',
      primary:               '#89b4fa',
      primaryForeground:     '#1e1e2e',
      secondary:             '#585b70',
      secondaryForeground:   '#cdd6f4',
      muted:                 '#6c7086',
      mutedForeground:       '#a6adc8',
      accent:                '#f5e0dc',
      accentForeground:      '#1e1e2e',
      destructive:           '#f38ba8',
      destructiveForeground: '#1e1e2e',
      border:                '#585b70',
      input:                 '#585b70',
      ring:                  '#89b4fa',
      chart1:                '#89b4fa',
      chart2:                '#f5e0dc',
      chart3:                '#a6e3a1',
      chart4:                '#f9e2af',
      chart5:                '#f5c2e7',
      sidebar:               '#181825',
    },
  },
  {
    name:         'gruvbox-light',
    displayName:  'Gruvbox Light',
    accentColors: [
      { name: 'red', displayName: 'Red', hex: '#cc241d' },
      { name: 'orange', displayName: 'Orange', hex: '#d65d0e' },
      { name: 'yellow', displayName: 'Yellow', hex: '#d79921' },
      { name: 'green', displayName: 'Green', hex: '#98971a' },
      { name: 'blue', displayName: 'Blue', hex: '#458588' },
      { name: 'purple', displayName: 'Purple', hex: '#b16286' },
      { name: 'pink', displayName: 'Pink', hex: '#d3869b' },
    ],
    colors: {
      background:            '#fbf1c7',
      foreground:            '#3c3836',
      card:                  '#fbf1c7',
      cardForeground:        '#3c3836',
      popover:               '#fbf1c7',
      popoverForeground:     '#3c3836',
      primary:               '#458588',
      primaryForeground:     '#fbf1c7',
      secondary:             '#ebdbb2',
      secondaryForeground:   '#3c3836',
      muted:                 '#d5c4a1',
      mutedForeground:       '#665c54',
      accent:                '#d79921',
      accentForeground:      '#fbf1c7',
      destructive:           '#cc241d',
      destructiveForeground: '#fbf1c7',
      border:                '#bdae93',
      input:                 '#bdae93',
      ring:                  '#458588',
      chart1:                '#458588',
      chart2:                '#d79921',
      chart3:                '#98971a',
      chart4:                '#d65d0e',
      chart5:                '#b16286',
      sidebar:               '#d5c4a1',
    },
  },
  {
    name:         'gruvbox-dark',
    displayName:  'Gruvbox Dark',
    accentColors: [
      { name: 'red', displayName: 'Red', hex: '#fb4934', foreground: '#282828' },
      { name: 'orange', displayName: 'Orange', hex: '#fe8019', foreground: '#282828' },
      { name: 'yellow', displayName: 'Yellow', hex: '#fabd2f', foreground: '#282828' },
      { name: 'green', displayName: 'Green', hex: '#b8bb26', foreground: '#282828' },
      { name: 'blue', displayName: 'Blue', hex: '#83a598', foreground: '#282828' },
      { name: 'purple', displayName: 'Purple', hex: '#d3869b', foreground: '#282828' },
      { name: 'pink', displayName: 'Pink', hex: '#d3869b', foreground: '#282828' },
    ],
    colors: {
      background:            '#282828',
      foreground:            '#ebdbb2',
      card:                  '#282828',
      cardForeground:        '#ebdbb2',
      popover:               '#282828',
      popoverForeground:     '#ebdbb2',
      primary:               '#83a598',
      primaryForeground:     '#282828',
      secondary:             '#504945',
      secondaryForeground:   '#ebdbb2',
      muted:                 '#665c54',
      mutedForeground:       '#a89984',
      accent:                '#fabd2f',
      accentForeground:      '#282828',
      destructive:           '#fb4934',
      destructiveForeground: '#282828',
      border:                '#504945',
      input:                 '#504945',
      ring:                  '#83a598',
      chart1:                '#83a598',
      chart2:                '#fabd2f',
      chart3:                '#b8bb26',
      chart4:                '#fe8019',
      chart5:                '#d3869b',
      sidebar:               '#1d2021',
    },
  },
]