// <auto-generated>
//     This file was generated by uniffi-bindgen-cs v0.10.0+v0.31.0
//     See https://github.com/NordSecurity/uniffi-bindgen-cs for more information.
// </auto-generated>

#nullable enable




using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
namespace aurelia_lyrics;



// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

[StructLayout(LayoutKind.Sequential)]
internal struct RustBuffer {
    public ulong capacity;
    public ulong len;
    public IntPtr data;

    public static RustBuffer Alloc(int size) {
        return _UniffiHelpers.RustCall((ref UniffiRustCallStatus status) => {
            var buffer = _UniFFILib.ffi_aurelia_lyrics_rustbuffer_alloc(Convert.ToUInt64(size), ref status);
            if (buffer.data == IntPtr.Zero) {
                throw new AllocationException($"RustBuffer.Alloc() returned null data pointer (size={size})");
            }
            return buffer;
        });
    }

    public static void Free(RustBuffer buffer) {
        _UniffiHelpers.RustCall((ref UniffiRustCallStatus status) => {
            _UniFFILib.ffi_aurelia_lyrics_rustbuffer_free(buffer, ref status);
        });
    }

    public static BigEndianStream MemoryStream(IntPtr data, long length)
    {
        unsafe
        {
            return new BigEndianStream(new UnmanagedMemoryStream((byte*)data.ToPointer(), length));
        }
    }

    public BigEndianStream AsStream()
    {
        unsafe
        {
            return new BigEndianStream(
                new UnmanagedMemoryStream((byte*)data.ToPointer(), Convert.ToInt64(len))
            );
        }
    }

    public BigEndianStream AsWriteableStream()
    {
        unsafe
        {
            return new BigEndianStream(
                new UnmanagedMemoryStream(
                    (byte*)data.ToPointer(),
                    Convert.ToInt64(capacity),
                    Convert.ToInt64(capacity),
                    FileAccess.Write
                )
            );
        }
    }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to managed memory, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

[StructLayout(LayoutKind.Sequential)]
internal struct ForeignBytes {
    public int length;
    public IntPtr data;
}


// The FfiConverter interface handles converter types to and from the FFI
//
// All implementing objects should be public to support external types.  When a
// type is external we need to import it's FfiConverter.
internal abstract class FfiConverter<CsType, FfiType> {
    // Convert an FFI type to a C# type
    public abstract CsType Lift(FfiType value);

    // Convert C# type to an FFI type
    public abstract FfiType Lower(CsType value);

    // Read a C# type from a `ByteBuffer`
    public abstract CsType Read(BigEndianStream stream);

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    public abstract int AllocationSize(CsType value);

    // Write a C# type to a `ByteBuffer`
    public abstract void Write(CsType value, BigEndianStream stream);

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    public RustBuffer LowerIntoRustBuffer(CsType value) {
        var rbuf = RustBuffer.Alloc(AllocationSize(value));
        try {
            var stream = rbuf.AsWriteableStream();
            Write(value, stream);
            rbuf.len = Convert.ToUInt64(stream.Position);
            return rbuf;
        } catch {
            RustBuffer.Free(rbuf);
            throw;
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    protected CsType LiftFromRustBuffer(RustBuffer rbuf) {
        var stream = rbuf.AsStream();
        try {
           var item = Read(stream);
           if (stream.HasRemaining()) {
               throw new InternalException("junk remaining in buffer after lifting, something is very wrong!!");
           }
           return item;
        } finally {
            RustBuffer.Free(rbuf);
        }
    }
}

// FfiConverter that uses `RustBuffer` as the FfiType
internal abstract class FfiConverterRustBuffer<CsType>: FfiConverter<CsType, RustBuffer> {
    public override CsType Lift(RustBuffer value) {
        return LiftFromRustBuffer(value);
    }
    public override RustBuffer Lower(CsType value) {
        return LowerIntoRustBuffer(value);
    }
}


// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.
// Error runtime.
[StructLayout(LayoutKind.Sequential)]
struct UniffiRustCallStatus {
    public sbyte code;
    public RustBuffer error_buf;

    public bool IsSuccess() {
        return code == 0;
    }

    public bool IsError() {
        return code == 1;
    }

    public bool IsPanic() {
        return code == 2;
    }
}

// Base class for all uniffi exceptions
public class UniffiException: System.Exception {
    public UniffiException(): base() {}
    public UniffiException(string message): base(message) {}
}

public class UndeclaredErrorException: UniffiException {
    public UndeclaredErrorException(string message): base(message) {}
}

public class PanicException: UniffiException {
    public PanicException(string message): base(message) {}
}

public class AllocationException: UniffiException {
    public AllocationException(string message): base(message) {}
}

public class InternalException: UniffiException {
    public InternalException(string message): base(message) {}
}

public class InvalidEnumException: InternalException {
    public InvalidEnumException(string message): base(message) {
    }
}

public class UniffiContractVersionException: UniffiException {
    public UniffiContractVersionException(string message): base(message) {
    }
}

public class UniffiContractChecksumException: UniffiException {
    public UniffiContractChecksumException(string message): base(message) {
    }
}

// Each top-level error class has a companion object that can lift the error from the call status's rust buffer
interface CallStatusErrorHandler<E> where E: System.Exception {
    E Lift(RustBuffer error_buf);
}

// CallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
class NullCallStatusErrorHandler: CallStatusErrorHandler<UniffiException> {
    public static NullCallStatusErrorHandler INSTANCE = new NullCallStatusErrorHandler();

    public UniffiException Lift(RustBuffer error_buf) {
        RustBuffer.Free(error_buf);
        return new UndeclaredErrorException("library has returned an error not declared in UNIFFI interface file");
    }
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself
class _UniffiHelpers {
    public delegate void RustCallAction(ref UniffiRustCallStatus status);
    public delegate U RustCallFunc<out U>(ref UniffiRustCallStatus status);

    // Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
    public static U RustCallWithError<U, E>(CallStatusErrorHandler<E> errorHandler, RustCallFunc<U> callback)
        where E: UniffiException
    {
        var status = new UniffiRustCallStatus();
        var return_value = callback(ref status);
        if (status.IsSuccess()) {
            return return_value;
        } else if (status.IsError()) {
            throw errorHandler.Lift(status.error_buf);
        } else if (status.IsPanic()) {
            // when the rust code sees a panic, it tries to construct a rustbuffer
            // with the message.  but if that code panics, then it just sends back
            // an empty buffer.
            if (status.error_buf.len > 0) {
                throw new PanicException(FfiConverterString.INSTANCE.Lift(status.error_buf));
            } else {
                throw new PanicException("Rust panic");
            }
        } else {
            throw new InternalException($"Unknown rust call status: {status.code}");
        }
    }

    // Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
    public static void RustCallWithError<E>(CallStatusErrorHandler<E> errorHandler, RustCallAction callback)
        where E: UniffiException
    {
        _UniffiHelpers.RustCallWithError(errorHandler, (ref UniffiRustCallStatus status) => {
            callback(ref status);
            return 0;
        });
    }

    // Call a rust function that returns a plain value
    public static U RustCall<U>(RustCallFunc<U> callback) {
        return _UniffiHelpers.RustCallWithError(NullCallStatusErrorHandler.INSTANCE, callback);
    }

    // Call a rust function that returns a plain value
    public static void RustCall(RustCallAction callback) {
        _UniffiHelpers.RustCall((ref UniffiRustCallStatus status) => {
            callback(ref status);
            return 0;
        });
    }
}

static class FFIObjectUtil {
    public static void DisposeAll(params Object?[] list) {
        Dispose(list);
    }

    // Dispose is implemented by recursive type inspection at runtime. This is because
    // generating correct Dispose calls for recursive complex types, e.g. List<List<int>>
    // is quite cumbersome.
   private static void Dispose(Object? obj) {
         if (obj == null) {
             return;
         }

         if (obj is IDisposable disposable) {
             disposable.Dispose();
             return;
         }

         var objType = obj.GetType();
         var typeCode = Type.GetTypeCode(objType);
         if (typeCode != TypeCode.Object) {
             return;
         }

         var genericArguments = objType.GetGenericArguments();
         if (genericArguments.Length == 0 && !objType.IsArray) {
             return;
         }

         if (obj is System.Collections.IDictionary objDictionary) {
             //This extra code tests to not call "Dispose" for a Dictionary<something, double>()
             //for all values as "double" and alike doesn't support interface "IDisposable"
             var valuesType = objType.GetGenericArguments()[1];
             var elementValuesTypeCode = Type.GetTypeCode(valuesType);
             if (elementValuesTypeCode != TypeCode.Object) {
                 return;
             }
             foreach (var value in objDictionary.Values) {
                 Dispose(value);
             }
         }
         else if (obj is System.Collections.IEnumerable listValues) {
             //This extra code tests to not call "Dispose" for a List<int>()
             //for all keys as "int" and alike doesn't support interface "IDisposable"
             var elementType = objType.IsArray ? objType.GetElementType() : genericArguments[0];
             var elementValuesTypeCode = Type.GetTypeCode(elementType);
             if (elementValuesTypeCode != TypeCode.Object) {
                 return;
             }
             foreach (var value in listValues) {
                 Dispose(value);
             }
         }
     }
}


// Big endian streams are not yet available in dotnet :'(
// https://github.com/dotnet/runtime/issues/26904

class StreamUnderflowException: System.Exception {
    public StreamUnderflowException() {
    }
}

static class BigEndianStreamExtensions
{
    public static void WriteInt32(this Stream stream, int value, int bytesToWrite = 4)
    {
#if DOTNET_8_0_OR_GREATER
        Span<byte> buffer = stackalloc byte[bytesToWrite];
#else
        byte[] buffer = new byte[bytesToWrite];
#endif
        var posByte = bytesToWrite;
        while (posByte != 0)
        {
            posByte--;
            buffer[posByte] = (byte)(value);
            value >>= 8;
        }

#if DOTNET_8_0_OR_GREATER
        stream.Write(buffer);
#else
        stream.Write(buffer, 0, buffer.Length);
#endif
    }

    public static void WriteInt64(this Stream stream, long value)
    {
        int bytesToWrite = 8;
#if DOTNET_8_0_OR_GREATER
         Span<byte> buffer = stackalloc byte[bytesToWrite];
 #else
         byte[] buffer = new byte[bytesToWrite];
 #endif
        var posByte = bytesToWrite;
        while (posByte != 0)
        {
            posByte--;
            buffer[posByte] = (byte)(value);
            value >>= 8;
        }

#if DOTNET_8_0_OR_GREATER
        stream.Write(buffer);
#else
        stream.Write(buffer, 0, buffer.Length);
#endif
    }

    public static uint ReadUint32(this Stream stream, int bytesToRead = 4) {
        CheckRemaining(stream, bytesToRead);
#if DOTNET_8_0_OR_GREATER
         Span<byte> buffer = stackalloc byte[bytesToRead];
         stream.Read(buffer);
#else
        byte[] buffer = new byte[bytesToRead];
        stream.Read(buffer, 0, bytesToRead);
#endif
        uint result = 0;
        uint digitMultiplier = 1;
        int posByte = bytesToRead;
        while (posByte != 0)
        {
            posByte--;
            result |= buffer[posByte]*digitMultiplier;
            digitMultiplier <<= 8;
        }

        return result;
    }

    public static ulong ReadUInt64(this Stream stream) {
        int bytesToRead = 8;
        CheckRemaining(stream, bytesToRead);
#if DOTNET_8_0_OR_GREATER
         Span<byte> buffer = stackalloc byte[bytesToRead];
         stream.Read(buffer);
#else
        byte[] buffer = new byte[bytesToRead];
        stream.Read(buffer, 0, bytesToRead);
#endif
        ulong result = 0;
        ulong digitMultiplier = 1;
        int posByte = bytesToRead;
        while (posByte != 0)
        {
            posByte--;
            result |= buffer[posByte]*digitMultiplier;
            digitMultiplier <<= 8;
        }

        return result;
    }

    public static void CheckRemaining(this Stream stream, int length) {
        if (stream.Length - stream.Position < length) {
            throw new StreamUnderflowException();
        }
    }

    public static void ForEach<T>(this T[] items, Action<T> action){
        foreach (var item in items) {
            action(item);
        }
    }
}

class BigEndianStream {
    Stream stream;
    public BigEndianStream(Stream stream) {
        this.stream = stream;
    }

    public bool HasRemaining() {
        return (stream.Length - Position) > 0;
    }

    public long Position {
        get => stream.Position;
        set => stream.Position = value;
    }

    public void WriteBytes(byte[] buffer) {
#if DOTNET_8_0_OR_GREATER
        stream.Write(buffer);
#else
        stream.Write(buffer, 0, buffer.Length);
#endif
    }

    public void WriteByte(byte value) => stream.WriteInt32(value, bytesToWrite: 1);
    public void WriteSByte(sbyte value) => stream.WriteInt32(value, bytesToWrite: 1);

    public void WriteUShort(ushort value) => stream.WriteInt32(value, bytesToWrite: 2);
    public void WriteShort(short value) => stream.WriteInt32(value, bytesToWrite: 2);

    public void WriteUInt(uint value) => stream.WriteInt32((int)value);
    public void WriteInt(int value) => stream.WriteInt32(value);

    public void WriteULong(ulong value) => stream.WriteInt64((long)value);
    public void WriteLong(long value) => stream.WriteInt64(value);

    public void WriteFloat(float value) {
        unsafe {
            WriteInt(*((int*)&value));
        }
    }
    public void WriteDouble(double value) => stream.WriteInt64(BitConverter.DoubleToInt64Bits(value));

    public byte[] ReadBytes(int length) {
        stream.CheckRemaining(length);
        byte[] result = new byte[length];
        stream.Read(result, 0, length);
        return result;
    }

    public byte ReadByte() => (byte)stream.ReadUint32(bytesToRead: 1);
    public ushort ReadUShort() => (ushort)stream.ReadUint32(bytesToRead: 2);
    public uint ReadUInt() => (uint)stream.ReadUint32(bytesToRead: 4);
    public ulong ReadULong() => stream.ReadUInt64();

    public sbyte ReadSByte() => (sbyte)ReadByte();
    public short ReadShort() => (short)ReadUShort();
    public int ReadInt() => (int)ReadUInt();

    public float ReadFloat() {
        unsafe {
            int value = ReadInt();
            return *((float*)&value);
        }
    }

    public long ReadLong() => (long)ReadULong();
    public double ReadDouble() => BitConverter.Int64BitsToDouble(ReadLong());
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.


// This is an implementation detail that will be called internally by the public API.
static partial class _UniFFILib {
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiRustFutureContinuationCallback(
        ulong @data,sbyte @pollResult
    );
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureDroppedCallback(
        ulong @handle
    );
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiCallbackInterfaceFree(
        ulong @handle
    );
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate ulong UniffiCallbackInterfaceClone(
        ulong @handle
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureDroppedCallbackStruct
    {
        public ulong @handle;
        public IntPtr @free;
    }
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultU8
    {
        public byte @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteU8(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureResultU8 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultI8
    {
        public sbyte @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteI8(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureResultI8 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultU16
    {
        public ushort @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteU16(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureResultU16 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultI16
    {
        public short @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteI16(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureResultI16 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultU32
    {
        public uint @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteU32(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureResultU32 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultI32
    {
        public int @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteI32(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureResultI32 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultU64
    {
        public ulong @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteU64(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureResultU64 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultI64
    {
        public long @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteI64(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureResultI64 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultF32
    {
        public float @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteF32(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureResultF32 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultF64
    {
        public double @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteF64(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureResultF64 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultRustBuffer
    {
        public RustBuffer @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteRustBuffer(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureResultRustBuffer @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultVoid
    {
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteVoid(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureResultVoid @result
    );
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

    static _UniFFILib() {
        _UniFFILib.uniffiCheckContractApiVersion();
        _UniFFILib.uniffiCheckApiChecksums();
        
        }

    [DllImport("aurelia_core", CallingConvention = CallingConvention.Cdecl)]
    public static extern RustBuffer ffi_aurelia_lyrics_rustbuffer_alloc(ulong @size,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("aurelia_core", CallingConvention = CallingConvention.Cdecl)]
    public static extern RustBuffer ffi_aurelia_lyrics_rustbuffer_from_bytes(ForeignBytes @bytes,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("aurelia_core", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_aurelia_lyrics_rustbuffer_free(RustBuffer @buf,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("aurelia_core", CallingConvention = CallingConvention.Cdecl)]
    public static extern RustBuffer ffi_aurelia_lyrics_rustbuffer_reserve(RustBuffer @buf,ulong @additional,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("aurelia_core", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_aurelia_lyrics_rust_future_poll_u8(ulong @handle,IntPtr @callback,ulong @callbackData
    );

    [DllImport("aurelia_core", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_aurelia_lyrics_rust_future_cancel_u8(ulong @handle
    );

    [DllImport("aurelia_core", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_aurelia_lyrics_rust_future_free_u8(ulong @handle
    );

    [DllImport("aurelia_core", CallingConvention = CallingConvention.Cdecl)]
    public static extern byte ffi_aurelia_lyrics_rust_future_complete_u8(ulong @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("aurelia_core", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_aurelia_lyrics_rust_future_poll_i8(ulong @handle,IntPtr @callback,ulong @callbackData
    );

    [DllImport("aurelia_core", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_aurelia_lyrics_rust_future_cancel_i8(ulong @handle
    );

    [DllImport("aurelia_core", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_aurelia_lyrics_rust_future_free_i8(ulong @handle
    );

    [DllImport("aurelia_core", CallingConvention = CallingConvention.Cdecl)]
    public static extern sbyte ffi_aurelia_lyrics_rust_future_complete_i8(ulong @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("aurelia_core", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_aurelia_lyrics_rust_future_poll_u16(ulong @handle,IntPtr @callback,ulong @callbackData
    );

    [DllImport("aurelia_core", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_aurelia_lyrics_rust_future_cancel_u16(ulong @handle
    );

    [DllImport("aurelia_core", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_aurelia_lyrics_rust_future_free_u16(ulong @handle
    );

    [DllImport("aurelia_core", CallingConvention = CallingConvention.Cdecl)]
    public static extern ushort ffi_aurelia_lyrics_rust_future_complete_u16(ulong @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("aurelia_core", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_aurelia_lyrics_rust_future_poll_i16(ulong @handle,IntPtr @callback,ulong @callbackData
    );

    [DllImport("aurelia_core", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_aurelia_lyrics_rust_future_cancel_i16(ulong @handle
    );

    [DllImport("aurelia_core", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_aurelia_lyrics_rust_future_free_i16(ulong @handle
    );

    [DllImport("aurelia_core", CallingConvention = CallingConvention.Cdecl)]
    public static extern short ffi_aurelia_lyrics_rust_future_complete_i16(ulong @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("aurelia_core", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_aurelia_lyrics_rust_future_poll_u32(ulong @handle,IntPtr @callback,ulong @callbackData
    );

    [DllImport("aurelia_core", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_aurelia_lyrics_rust_future_cancel_u32(ulong @handle
    );

    [DllImport("aurelia_core", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_aurelia_lyrics_rust_future_free_u32(ulong @handle
    );

    [DllImport("aurelia_core", CallingConvention = CallingConvention.Cdecl)]
    public static extern uint ffi_aurelia_lyrics_rust_future_complete_u32(ulong @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("aurelia_core", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_aurelia_lyrics_rust_future_poll_i32(ulong @handle,IntPtr @callback,ulong @callbackData
    );

    [DllImport("aurelia_core", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_aurelia_lyrics_rust_future_cancel_i32(ulong @handle
    );

    [DllImport("aurelia_core", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_aurelia_lyrics_rust_future_free_i32(ulong @handle
    );

    [DllImport("aurelia_core", CallingConvention = CallingConvention.Cdecl)]
    public static extern int ffi_aurelia_lyrics_rust_future_complete_i32(ulong @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("aurelia_core", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_aurelia_lyrics_rust_future_poll_u64(ulong @handle,IntPtr @callback,ulong @callbackData
    );

    [DllImport("aurelia_core", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_aurelia_lyrics_rust_future_cancel_u64(ulong @handle
    );

    [DllImport("aurelia_core", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_aurelia_lyrics_rust_future_free_u64(ulong @handle
    );

    [DllImport("aurelia_core", CallingConvention = CallingConvention.Cdecl)]
    public static extern ulong ffi_aurelia_lyrics_rust_future_complete_u64(ulong @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("aurelia_core", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_aurelia_lyrics_rust_future_poll_i64(ulong @handle,IntPtr @callback,ulong @callbackData
    );

    [DllImport("aurelia_core", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_aurelia_lyrics_rust_future_cancel_i64(ulong @handle
    );

    [DllImport("aurelia_core", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_aurelia_lyrics_rust_future_free_i64(ulong @handle
    );

    [DllImport("aurelia_core", CallingConvention = CallingConvention.Cdecl)]
    public static extern long ffi_aurelia_lyrics_rust_future_complete_i64(ulong @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("aurelia_core", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_aurelia_lyrics_rust_future_poll_f32(ulong @handle,IntPtr @callback,ulong @callbackData
    );

    [DllImport("aurelia_core", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_aurelia_lyrics_rust_future_cancel_f32(ulong @handle
    );

    [DllImport("aurelia_core", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_aurelia_lyrics_rust_future_free_f32(ulong @handle
    );

    [DllImport("aurelia_core", CallingConvention = CallingConvention.Cdecl)]
    public static extern float ffi_aurelia_lyrics_rust_future_complete_f32(ulong @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("aurelia_core", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_aurelia_lyrics_rust_future_poll_f64(ulong @handle,IntPtr @callback,ulong @callbackData
    );

    [DllImport("aurelia_core", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_aurelia_lyrics_rust_future_cancel_f64(ulong @handle
    );

    [DllImport("aurelia_core", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_aurelia_lyrics_rust_future_free_f64(ulong @handle
    );

    [DllImport("aurelia_core", CallingConvention = CallingConvention.Cdecl)]
    public static extern double ffi_aurelia_lyrics_rust_future_complete_f64(ulong @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("aurelia_core", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_aurelia_lyrics_rust_future_poll_rust_buffer(ulong @handle,IntPtr @callback,ulong @callbackData
    );

    [DllImport("aurelia_core", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_aurelia_lyrics_rust_future_cancel_rust_buffer(ulong @handle
    );

    [DllImport("aurelia_core", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_aurelia_lyrics_rust_future_free_rust_buffer(ulong @handle
    );

    [DllImport("aurelia_core", CallingConvention = CallingConvention.Cdecl)]
    public static extern RustBuffer ffi_aurelia_lyrics_rust_future_complete_rust_buffer(ulong @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("aurelia_core", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_aurelia_lyrics_rust_future_poll_void(ulong @handle,IntPtr @callback,ulong @callbackData
    );

    [DllImport("aurelia_core", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_aurelia_lyrics_rust_future_cancel_void(ulong @handle
    );

    [DllImport("aurelia_core", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_aurelia_lyrics_rust_future_free_void(ulong @handle
    );

    [DllImport("aurelia_core", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_aurelia_lyrics_rust_future_complete_void(ulong @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("aurelia_core", CallingConvention = CallingConvention.Cdecl)]
    public static extern uint ffi_aurelia_lyrics_uniffi_contract_version(
    );

    

    static void uniffiCheckContractApiVersion() {
        var scaffolding_contract_version = _UniFFILib.ffi_aurelia_lyrics_uniffi_contract_version();
        if (30 != scaffolding_contract_version) {
            throw new UniffiContractVersionException($"aurelia_lyrics: uniffi bindings expected version `30`, library returned `{scaffolding_contract_version}`");
        }
    }

    static void uniffiCheckApiChecksums() {
    }
}

// Public interface members begin here.

#pragma warning disable 8625




class FfiConverterInt64: FfiConverter<long, long> {
    public static FfiConverterInt64 INSTANCE = new FfiConverterInt64();

    public override long Lift(long value) {
        return value;
    }

    public override long Read(BigEndianStream stream) {
        return stream.ReadLong();
    }

    public override long Lower(long value) {
        return value;
    }

    public override int AllocationSize(long value) {
        return 8;
    }

    public override void Write(long value, BigEndianStream stream) {
        stream.WriteLong(value);
    }
}



class FfiConverterBoolean: FfiConverter<bool, sbyte> {
    public static FfiConverterBoolean INSTANCE = new FfiConverterBoolean();

    public override bool Lift(sbyte value) {
        return value != 0;
    }

    public override bool Read(BigEndianStream stream) {
        return Lift(stream.ReadSByte());
    }

    public override sbyte Lower(bool value) {
        return value ? (sbyte)1 : (sbyte)0;
    }

    public override int AllocationSize(bool value) {
        return (sbyte)1;
    }

    public override void Write(bool value, BigEndianStream stream) {
        stream.WriteSByte(Lower(value));
    }
}



class FfiConverterString: FfiConverter<string, RustBuffer> {
    public static FfiConverterString INSTANCE = new FfiConverterString();

    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    public override string Lift(RustBuffer value) {
        try {
            var bytes = value.AsStream().ReadBytes(Convert.ToInt32(value.len));
            return System.Text.Encoding.UTF8.GetString(bytes);
        } finally {
            RustBuffer.Free(value);
        }
    }

    public override string Read(BigEndianStream stream) {
        var length = stream.ReadInt();
        var bytes = stream.ReadBytes(length);
        return System.Text.Encoding.UTF8.GetString(bytes);
    }

    public override RustBuffer Lower(string value) {
        var bytes = System.Text.Encoding.UTF8.GetBytes(value);
        var rbuf = RustBuffer.Alloc(bytes.Length);
        rbuf.AsWriteableStream().WriteBytes(bytes);
        return rbuf;
    }

    // TODO(CS)
    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per unicode codepoint which will always be
    // enough.
    public override int AllocationSize(string value) {
        const int sizeForLength = 4;
        var sizeForString = System.Text.Encoding.UTF8.GetByteCount(value);
        return sizeForLength + sizeForString;
    }

    public override void Write(string value, BigEndianStream stream) {
        var bytes = System.Text.Encoding.UTF8.GetBytes(value);
        stream.WriteInt(bytes.Length);
        stream.WriteBytes(bytes);
    }
}



/// <summary>
/// Parsed lyrics payload returned by shared parser.
/// </summary>
public record ParsedLyrics (
    string[] @plain, 
    ParsedLyricsLine[] @synced, 
    ParsedLyricsSection[]? @sections, 
    ParsedLyricsAgent[]? @agents, 
    string[]? @songwriters, 
    string? @language, 
    bool @areFromRemote
) {
}

class FfiConverterTypeParsedLyrics: FfiConverterRustBuffer<ParsedLyrics> {
    public static FfiConverterTypeParsedLyrics INSTANCE = new FfiConverterTypeParsedLyrics();

    public override ParsedLyrics Read(BigEndianStream stream) {
        return new ParsedLyrics(
            @plain: FfiConverterSequenceString.INSTANCE.Read(stream),
            @synced: FfiConverterSequenceTypeParsedLyricsLine.INSTANCE.Read(stream),
            @sections: FfiConverterOptionalSequenceTypeParsedLyricsSection.INSTANCE.Read(stream),
            @agents: FfiConverterOptionalSequenceTypeParsedLyricsAgent.INSTANCE.Read(stream),
            @songwriters: FfiConverterOptionalSequenceString.INSTANCE.Read(stream),
            @language: FfiConverterOptionalString.INSTANCE.Read(stream),
            @areFromRemote: FfiConverterBoolean.INSTANCE.Read(stream)
        );
    }

    public override int AllocationSize(ParsedLyrics value) {
        return 0
            + FfiConverterSequenceString.INSTANCE.AllocationSize(value.@plain)
            + FfiConverterSequenceTypeParsedLyricsLine.INSTANCE.AllocationSize(value.@synced)
            + FfiConverterOptionalSequenceTypeParsedLyricsSection.INSTANCE.AllocationSize(value.@sections)
            + FfiConverterOptionalSequenceTypeParsedLyricsAgent.INSTANCE.AllocationSize(value.@agents)
            + FfiConverterOptionalSequenceString.INSTANCE.AllocationSize(value.@songwriters)
            + FfiConverterOptionalString.INSTANCE.AllocationSize(value.@language)
            + FfiConverterBoolean.INSTANCE.AllocationSize(value.@areFromRemote);
    }

    public override void Write(ParsedLyrics value, BigEndianStream stream) {
            FfiConverterSequenceString.INSTANCE.Write(value.@plain, stream);
            FfiConverterSequenceTypeParsedLyricsLine.INSTANCE.Write(value.@synced, stream);
            FfiConverterOptionalSequenceTypeParsedLyricsSection.INSTANCE.Write(value.@sections, stream);
            FfiConverterOptionalSequenceTypeParsedLyricsAgent.INSTANCE.Write(value.@agents, stream);
            FfiConverterOptionalSequenceString.INSTANCE.Write(value.@songwriters, stream);
            FfiConverterOptionalString.INSTANCE.Write(value.@language, stream);
            FfiConverterBoolean.INSTANCE.Write(value.@areFromRemote, stream);
    }
}



/// <summary>
/// A singer/performer agent definition.
/// </summary>
/// <param name="id">
/// Unique identifier (e.g. "v1", "v2000").
/// </param>
/// <param name="agent_type">
/// Agent type: "person" for a singer, "other" for background/samples.
/// </param>
public record ParsedLyricsAgent (
    /// <summary>
    /// Unique identifier (e.g. "v1", "v2000").
    /// </summary>
    string @id, 
    /// <summary>
    /// Agent type: "person" for a singer, "other" for background/samples.
    /// </summary>
    string @agentType
) {
}

class FfiConverterTypeParsedLyricsAgent: FfiConverterRustBuffer<ParsedLyricsAgent> {
    public static FfiConverterTypeParsedLyricsAgent INSTANCE = new FfiConverterTypeParsedLyricsAgent();

    public override ParsedLyricsAgent Read(BigEndianStream stream) {
        return new ParsedLyricsAgent(
            @id: FfiConverterString.INSTANCE.Read(stream),
            @agentType: FfiConverterString.INSTANCE.Read(stream)
        );
    }

    public override int AllocationSize(ParsedLyricsAgent value) {
        return 0
            + FfiConverterString.INSTANCE.AllocationSize(value.@id)
            + FfiConverterString.INSTANCE.AllocationSize(value.@agentType);
    }

    public override void Write(ParsedLyricsAgent value, BigEndianStream stream) {
            FfiConverterString.INSTANCE.Write(value.@id, stream);
            FfiConverterString.INSTANCE.Write(value.@agentType, stream);
    }
}



/// <summary>
/// Line-level synchronized lyric entry.
/// </summary>
/// <param name="agent_id">
/// Agent/singer identifier (e.g. "v1", "v2000") for multi-singer attribution.
/// </param>
/// <param name="translation">
/// Translation text for this line, if available (e.g. English translation of foreign lyrics).
/// </param>
public record ParsedLyricsLine (
    long @timeMs, 
    long? @endTimeMs, 
    string @line, 
    ParsedLyricsWord[]? @words, 
    /// <summary>
    /// Agent/singer identifier (e.g. "v1", "v2000") for multi-singer attribution.
    /// </summary>
    string? @agentId, 
    /// <summary>
    /// Translation text for this line, if available (e.g. English translation of foreign lyrics).
    /// </summary>
    string? @translation
) {
}

class FfiConverterTypeParsedLyricsLine: FfiConverterRustBuffer<ParsedLyricsLine> {
    public static FfiConverterTypeParsedLyricsLine INSTANCE = new FfiConverterTypeParsedLyricsLine();

    public override ParsedLyricsLine Read(BigEndianStream stream) {
        return new ParsedLyricsLine(
            @timeMs: FfiConverterInt64.INSTANCE.Read(stream),
            @endTimeMs: FfiConverterOptionalInt64.INSTANCE.Read(stream),
            @line: FfiConverterString.INSTANCE.Read(stream),
            @words: FfiConverterOptionalSequenceTypeParsedLyricsWord.INSTANCE.Read(stream),
            @agentId: FfiConverterOptionalString.INSTANCE.Read(stream),
            @translation: FfiConverterOptionalString.INSTANCE.Read(stream)
        );
    }

    public override int AllocationSize(ParsedLyricsLine value) {
        return 0
            + FfiConverterInt64.INSTANCE.AllocationSize(value.@timeMs)
            + FfiConverterOptionalInt64.INSTANCE.AllocationSize(value.@endTimeMs)
            + FfiConverterString.INSTANCE.AllocationSize(value.@line)
            + FfiConverterOptionalSequenceTypeParsedLyricsWord.INSTANCE.AllocationSize(value.@words)
            + FfiConverterOptionalString.INSTANCE.AllocationSize(value.@agentId)
            + FfiConverterOptionalString.INSTANCE.AllocationSize(value.@translation);
    }

    public override void Write(ParsedLyricsLine value, BigEndianStream stream) {
            FfiConverterInt64.INSTANCE.Write(value.@timeMs, stream);
            FfiConverterOptionalInt64.INSTANCE.Write(value.@endTimeMs, stream);
            FfiConverterString.INSTANCE.Write(value.@line, stream);
            FfiConverterOptionalSequenceTypeParsedLyricsWord.INSTANCE.Write(value.@words, stream);
            FfiConverterOptionalString.INSTANCE.Write(value.@agentId, stream);
            FfiConverterOptionalString.INSTANCE.Write(value.@translation, stream);
    }
}



/// <summary>
/// A named section of the song (e.g. Verse, Chorus, Bridge).
/// </summary>
/// <param name="name">
/// Section name (e.g. "Verse", "Chorus", "Bridge", "Intro", "Outro").
/// </param>
/// <param name="start_time_ms">
/// Start time in milliseconds.
/// </param>
/// <param name="end_time_ms">
/// End time in milliseconds.
/// </param>
/// <param name="lines">
/// Lines belonging to this section.
/// </param>
/// <param name="agent_id">
/// Default agent for this section, if any.
/// </param>
public record ParsedLyricsSection (
    /// <summary>
    /// Section name (e.g. "Verse", "Chorus", "Bridge", "Intro", "Outro").
    /// </summary>
    string @name, 
    /// <summary>
    /// Start time in milliseconds.
    /// </summary>
    long @startTimeMs, 
    /// <summary>
    /// End time in milliseconds.
    /// </summary>
    long @endTimeMs, 
    /// <summary>
    /// Lines belonging to this section.
    /// </summary>
    ParsedLyricsLine[] @lines, 
    /// <summary>
    /// Default agent for this section, if any.
    /// </summary>
    string? @agentId
) {
}

class FfiConverterTypeParsedLyricsSection: FfiConverterRustBuffer<ParsedLyricsSection> {
    public static FfiConverterTypeParsedLyricsSection INSTANCE = new FfiConverterTypeParsedLyricsSection();

    public override ParsedLyricsSection Read(BigEndianStream stream) {
        return new ParsedLyricsSection(
            @name: FfiConverterString.INSTANCE.Read(stream),
            @startTimeMs: FfiConverterInt64.INSTANCE.Read(stream),
            @endTimeMs: FfiConverterInt64.INSTANCE.Read(stream),
            @lines: FfiConverterSequenceTypeParsedLyricsLine.INSTANCE.Read(stream),
            @agentId: FfiConverterOptionalString.INSTANCE.Read(stream)
        );
    }

    public override int AllocationSize(ParsedLyricsSection value) {
        return 0
            + FfiConverterString.INSTANCE.AllocationSize(value.@name)
            + FfiConverterInt64.INSTANCE.AllocationSize(value.@startTimeMs)
            + FfiConverterInt64.INSTANCE.AllocationSize(value.@endTimeMs)
            + FfiConverterSequenceTypeParsedLyricsLine.INSTANCE.AllocationSize(value.@lines)
            + FfiConverterOptionalString.INSTANCE.AllocationSize(value.@agentId);
    }

    public override void Write(ParsedLyricsSection value, BigEndianStream stream) {
            FfiConverterString.INSTANCE.Write(value.@name, stream);
            FfiConverterInt64.INSTANCE.Write(value.@startTimeMs, stream);
            FfiConverterInt64.INSTANCE.Write(value.@endTimeMs, stream);
            FfiConverterSequenceTypeParsedLyricsLine.INSTANCE.Write(value.@lines, stream);
            FfiConverterOptionalString.INSTANCE.Write(value.@agentId, stream);
    }
}



/// <summary>
/// Word-level synchronized lyric entry.
/// </summary>
public record ParsedLyricsWord (
    long @timeMs, 
    long? @endTimeMs, 
    string @word
) {
}

class FfiConverterTypeParsedLyricsWord: FfiConverterRustBuffer<ParsedLyricsWord> {
    public static FfiConverterTypeParsedLyricsWord INSTANCE = new FfiConverterTypeParsedLyricsWord();

    public override ParsedLyricsWord Read(BigEndianStream stream) {
        return new ParsedLyricsWord(
            @timeMs: FfiConverterInt64.INSTANCE.Read(stream),
            @endTimeMs: FfiConverterOptionalInt64.INSTANCE.Read(stream),
            @word: FfiConverterString.INSTANCE.Read(stream)
        );
    }

    public override int AllocationSize(ParsedLyricsWord value) {
        return 0
            + FfiConverterInt64.INSTANCE.AllocationSize(value.@timeMs)
            + FfiConverterOptionalInt64.INSTANCE.AllocationSize(value.@endTimeMs)
            + FfiConverterString.INSTANCE.AllocationSize(value.@word);
    }

    public override void Write(ParsedLyricsWord value, BigEndianStream stream) {
            FfiConverterInt64.INSTANCE.Write(value.@timeMs, stream);
            FfiConverterOptionalInt64.INSTANCE.Write(value.@endTimeMs, stream);
            FfiConverterString.INSTANCE.Write(value.@word, stream);
    }
}




class FfiConverterOptionalInt64: FfiConverterRustBuffer<long?> {
    public static FfiConverterOptionalInt64 INSTANCE = new FfiConverterOptionalInt64();

    public override long? Read(BigEndianStream stream) {
        if (stream.ReadByte() == 0) {
            return null;
        }
        return FfiConverterInt64.INSTANCE.Read(stream);
    }

    public override int AllocationSize(long? value) {
        if (value == null) {
            return 1;
        } else {
            return 1 + FfiConverterInt64.INSTANCE.AllocationSize((long)value);
        }
    }

    public override void Write(long? value, BigEndianStream stream) {
        if (value == null) {
            stream.WriteByte(0);
        } else {
            stream.WriteByte(1);
            FfiConverterInt64.INSTANCE.Write((long)value, stream);
        }
    }
}




class FfiConverterOptionalString: FfiConverterRustBuffer<string?> {
    public static FfiConverterOptionalString INSTANCE = new FfiConverterOptionalString();

    public override string? Read(BigEndianStream stream) {
        if (stream.ReadByte() == 0) {
            return null;
        }
        return FfiConverterString.INSTANCE.Read(stream);
    }

    public override int AllocationSize(string? value) {
        if (value == null) {
            return 1;
        } else {
            return 1 + FfiConverterString.INSTANCE.AllocationSize((string)value);
        }
    }

    public override void Write(string? value, BigEndianStream stream) {
        if (value == null) {
            stream.WriteByte(0);
        } else {
            stream.WriteByte(1);
            FfiConverterString.INSTANCE.Write((string)value, stream);
        }
    }
}




class FfiConverterOptionalSequenceString: FfiConverterRustBuffer<string[]?> {
    public static FfiConverterOptionalSequenceString INSTANCE = new FfiConverterOptionalSequenceString();

    public override string[]? Read(BigEndianStream stream) {
        if (stream.ReadByte() == 0) {
            return null;
        }
        return FfiConverterSequenceString.INSTANCE.Read(stream);
    }

    public override int AllocationSize(string[]? value) {
        if (value == null) {
            return 1;
        } else {
            return 1 + FfiConverterSequenceString.INSTANCE.AllocationSize((string[])value);
        }
    }

    public override void Write(string[]? value, BigEndianStream stream) {
        if (value == null) {
            stream.WriteByte(0);
        } else {
            stream.WriteByte(1);
            FfiConverterSequenceString.INSTANCE.Write((string[])value, stream);
        }
    }
}




class FfiConverterOptionalSequenceTypeParsedLyricsAgent: FfiConverterRustBuffer<ParsedLyricsAgent[]?> {
    public static FfiConverterOptionalSequenceTypeParsedLyricsAgent INSTANCE = new FfiConverterOptionalSequenceTypeParsedLyricsAgent();

    public override ParsedLyricsAgent[]? Read(BigEndianStream stream) {
        if (stream.ReadByte() == 0) {
            return null;
        }
        return FfiConverterSequenceTypeParsedLyricsAgent.INSTANCE.Read(stream);
    }

    public override int AllocationSize(ParsedLyricsAgent[]? value) {
        if (value == null) {
            return 1;
        } else {
            return 1 + FfiConverterSequenceTypeParsedLyricsAgent.INSTANCE.AllocationSize((ParsedLyricsAgent[])value);
        }
    }

    public override void Write(ParsedLyricsAgent[]? value, BigEndianStream stream) {
        if (value == null) {
            stream.WriteByte(0);
        } else {
            stream.WriteByte(1);
            FfiConverterSequenceTypeParsedLyricsAgent.INSTANCE.Write((ParsedLyricsAgent[])value, stream);
        }
    }
}




class FfiConverterOptionalSequenceTypeParsedLyricsSection: FfiConverterRustBuffer<ParsedLyricsSection[]?> {
    public static FfiConverterOptionalSequenceTypeParsedLyricsSection INSTANCE = new FfiConverterOptionalSequenceTypeParsedLyricsSection();

    public override ParsedLyricsSection[]? Read(BigEndianStream stream) {
        if (stream.ReadByte() == 0) {
            return null;
        }
        return FfiConverterSequenceTypeParsedLyricsSection.INSTANCE.Read(stream);
    }

    public override int AllocationSize(ParsedLyricsSection[]? value) {
        if (value == null) {
            return 1;
        } else {
            return 1 + FfiConverterSequenceTypeParsedLyricsSection.INSTANCE.AllocationSize((ParsedLyricsSection[])value);
        }
    }

    public override void Write(ParsedLyricsSection[]? value, BigEndianStream stream) {
        if (value == null) {
            stream.WriteByte(0);
        } else {
            stream.WriteByte(1);
            FfiConverterSequenceTypeParsedLyricsSection.INSTANCE.Write((ParsedLyricsSection[])value, stream);
        }
    }
}




class FfiConverterOptionalSequenceTypeParsedLyricsWord: FfiConverterRustBuffer<ParsedLyricsWord[]?> {
    public static FfiConverterOptionalSequenceTypeParsedLyricsWord INSTANCE = new FfiConverterOptionalSequenceTypeParsedLyricsWord();

    public override ParsedLyricsWord[]? Read(BigEndianStream stream) {
        if (stream.ReadByte() == 0) {
            return null;
        }
        return FfiConverterSequenceTypeParsedLyricsWord.INSTANCE.Read(stream);
    }

    public override int AllocationSize(ParsedLyricsWord[]? value) {
        if (value == null) {
            return 1;
        } else {
            return 1 + FfiConverterSequenceTypeParsedLyricsWord.INSTANCE.AllocationSize((ParsedLyricsWord[])value);
        }
    }

    public override void Write(ParsedLyricsWord[]? value, BigEndianStream stream) {
        if (value == null) {
            stream.WriteByte(0);
        } else {
            stream.WriteByte(1);
            FfiConverterSequenceTypeParsedLyricsWord.INSTANCE.Write((ParsedLyricsWord[])value, stream);
        }
    }
}




class FfiConverterSequenceString: FfiConverterRustBuffer<string[]> {
    public static FfiConverterSequenceString INSTANCE = new FfiConverterSequenceString();

    public override string[]  Read(BigEndianStream stream) {
        var length = stream.ReadInt();
        if (length == 0) {
            return [];
        }

        var result = new string[(length)];
        var readFn = FfiConverterString.INSTANCE.Read;
        for (int i = 0; i < length; i++) {
            result[i] = readFn(stream);
        }
        return result;
    }

    public override int AllocationSize(string[]  value) {
        var sizeForLength = 4;

        // details/1-empty-list-as-default-method-parameter.md
        if (value == null) {
            return sizeForLength;
        }

        var allocationSizeFn = FfiConverterString.INSTANCE.AllocationSize;
        var sizeForItems = value.Sum(item => allocationSizeFn(item));
        return sizeForLength + sizeForItems;
    }

    public override void Write(string[] value, BigEndianStream stream) {
        // details/1-empty-list-as-default-method-parameter.md
        if (value == null) {
            stream.WriteInt(0);
            return;
        }

        stream.WriteInt(value.Length);
        var writerFn = FfiConverterString.INSTANCE.Write;
        value.ForEach(item => writerFn(item, stream));
    }
}




class FfiConverterSequenceTypeParsedLyricsAgent: FfiConverterRustBuffer<ParsedLyricsAgent[]> {
    public static FfiConverterSequenceTypeParsedLyricsAgent INSTANCE = new FfiConverterSequenceTypeParsedLyricsAgent();

    public override ParsedLyricsAgent[]  Read(BigEndianStream stream) {
        var length = stream.ReadInt();
        if (length == 0) {
            return [];
        }

        var result = new ParsedLyricsAgent[(length)];
        var readFn = FfiConverterTypeParsedLyricsAgent.INSTANCE.Read;
        for (int i = 0; i < length; i++) {
            result[i] = readFn(stream);
        }
        return result;
    }

    public override int AllocationSize(ParsedLyricsAgent[]  value) {
        var sizeForLength = 4;

        // details/1-empty-list-as-default-method-parameter.md
        if (value == null) {
            return sizeForLength;
        }

        var allocationSizeFn = FfiConverterTypeParsedLyricsAgent.INSTANCE.AllocationSize;
        var sizeForItems = value.Sum(item => allocationSizeFn(item));
        return sizeForLength + sizeForItems;
    }

    public override void Write(ParsedLyricsAgent[] value, BigEndianStream stream) {
        // details/1-empty-list-as-default-method-parameter.md
        if (value == null) {
            stream.WriteInt(0);
            return;
        }

        stream.WriteInt(value.Length);
        var writerFn = FfiConverterTypeParsedLyricsAgent.INSTANCE.Write;
        value.ForEach(item => writerFn(item, stream));
    }
}




class FfiConverterSequenceTypeParsedLyricsLine: FfiConverterRustBuffer<ParsedLyricsLine[]> {
    public static FfiConverterSequenceTypeParsedLyricsLine INSTANCE = new FfiConverterSequenceTypeParsedLyricsLine();

    public override ParsedLyricsLine[]  Read(BigEndianStream stream) {
        var length = stream.ReadInt();
        if (length == 0) {
            return [];
        }

        var result = new ParsedLyricsLine[(length)];
        var readFn = FfiConverterTypeParsedLyricsLine.INSTANCE.Read;
        for (int i = 0; i < length; i++) {
            result[i] = readFn(stream);
        }
        return result;
    }

    public override int AllocationSize(ParsedLyricsLine[]  value) {
        var sizeForLength = 4;

        // details/1-empty-list-as-default-method-parameter.md
        if (value == null) {
            return sizeForLength;
        }

        var allocationSizeFn = FfiConverterTypeParsedLyricsLine.INSTANCE.AllocationSize;
        var sizeForItems = value.Sum(item => allocationSizeFn(item));
        return sizeForLength + sizeForItems;
    }

    public override void Write(ParsedLyricsLine[] value, BigEndianStream stream) {
        // details/1-empty-list-as-default-method-parameter.md
        if (value == null) {
            stream.WriteInt(0);
            return;
        }

        stream.WriteInt(value.Length);
        var writerFn = FfiConverterTypeParsedLyricsLine.INSTANCE.Write;
        value.ForEach(item => writerFn(item, stream));
    }
}




class FfiConverterSequenceTypeParsedLyricsSection: FfiConverterRustBuffer<ParsedLyricsSection[]> {
    public static FfiConverterSequenceTypeParsedLyricsSection INSTANCE = new FfiConverterSequenceTypeParsedLyricsSection();

    public override ParsedLyricsSection[]  Read(BigEndianStream stream) {
        var length = stream.ReadInt();
        if (length == 0) {
            return [];
        }

        var result = new ParsedLyricsSection[(length)];
        var readFn = FfiConverterTypeParsedLyricsSection.INSTANCE.Read;
        for (int i = 0; i < length; i++) {
            result[i] = readFn(stream);
        }
        return result;
    }

    public override int AllocationSize(ParsedLyricsSection[]  value) {
        var sizeForLength = 4;

        // details/1-empty-list-as-default-method-parameter.md
        if (value == null) {
            return sizeForLength;
        }

        var allocationSizeFn = FfiConverterTypeParsedLyricsSection.INSTANCE.AllocationSize;
        var sizeForItems = value.Sum(item => allocationSizeFn(item));
        return sizeForLength + sizeForItems;
    }

    public override void Write(ParsedLyricsSection[] value, BigEndianStream stream) {
        // details/1-empty-list-as-default-method-parameter.md
        if (value == null) {
            stream.WriteInt(0);
            return;
        }

        stream.WriteInt(value.Length);
        var writerFn = FfiConverterTypeParsedLyricsSection.INSTANCE.Write;
        value.ForEach(item => writerFn(item, stream));
    }
}




class FfiConverterSequenceTypeParsedLyricsWord: FfiConverterRustBuffer<ParsedLyricsWord[]> {
    public static FfiConverterSequenceTypeParsedLyricsWord INSTANCE = new FfiConverterSequenceTypeParsedLyricsWord();

    public override ParsedLyricsWord[]  Read(BigEndianStream stream) {
        var length = stream.ReadInt();
        if (length == 0) {
            return [];
        }

        var result = new ParsedLyricsWord[(length)];
        var readFn = FfiConverterTypeParsedLyricsWord.INSTANCE.Read;
        for (int i = 0; i < length; i++) {
            result[i] = readFn(stream);
        }
        return result;
    }

    public override int AllocationSize(ParsedLyricsWord[]  value) {
        var sizeForLength = 4;

        // details/1-empty-list-as-default-method-parameter.md
        if (value == null) {
            return sizeForLength;
        }

        var allocationSizeFn = FfiConverterTypeParsedLyricsWord.INSTANCE.AllocationSize;
        var sizeForItems = value.Sum(item => allocationSizeFn(item));
        return sizeForLength + sizeForItems;
    }

    public override void Write(ParsedLyricsWord[] value, BigEndianStream stream) {
        // details/1-empty-list-as-default-method-parameter.md
        if (value == null) {
            stream.WriteInt(0);
            return;
        }

        stream.WriteInt(value.Length);
        var writerFn = FfiConverterTypeParsedLyricsWord.INSTANCE.Write;
        value.ForEach(item => writerFn(item, stream));
    }
}
#pragma warning restore 8625
public static class AureliaLyrics {
}

