/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

// This is a stub created for initial type-checking before the dev server generates the actual file.

declare module 'vue-router/auto-routes' {
  import type { RouteRecordRaw, Router } from 'vue-router'

  export const routes: RouteRecordRaw[]
  export function handleHotUpdate(router: Router): void
}
