/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/albums/': RouteRecordInfo<
      '/albums/',
      '/albums',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/albums/[id]': RouteRecordInfo<
      '/albums/[id]',
      '/albums/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/artists/': RouteRecordInfo<
      '/artists/',
      '/artists',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/artists/[id]': RouteRecordInfo<
      '/artists/[id]',
      '/artists/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/playlists/': RouteRecordInfo<
      '/playlists/',
      '/playlists',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/playlists/[id]': RouteRecordInfo<
      '/playlists/[id]',
      '/playlists/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/playlists/[id].edit': RouteRecordInfo<
      '/playlists/[id].edit',
      '/playlists/:id/edit',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/playlists/create': RouteRecordInfo<
      '/playlists/create',
      '/playlists/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings': RouteRecordInfo<
      '/settings',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/songs/': RouteRecordInfo<
      '/songs/',
      '/songs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/albums/index.vue': {
      routes:
        | '/albums/'
      views:
        | never
    }
    'src/pages/albums/[id].vue': {
      routes:
        | '/albums/[id]'
      views:
        | never
    }
    'src/pages/artists/index.vue': {
      routes:
        | '/artists/'
      views:
        | never
    }
    'src/pages/artists/[id].vue': {
      routes:
        | '/artists/[id]'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
    'src/pages/playlists/index.vue': {
      routes:
        | '/playlists/'
      views:
        | never
    }
    'src/pages/playlists/[id].vue': {
      routes:
        | '/playlists/[id]'
      views:
        | never
    }
    'src/pages/playlists/[id].edit.vue': {
      routes:
        | '/playlists/[id].edit'
      views:
        | never
    }
    'src/pages/playlists/create.vue': {
      routes:
        | '/playlists/create'
      views:
        | never
    }
    'src/pages/settings.vue': {
      routes:
        | '/settings'
      views:
        | never
    }
    'src/pages/songs/index.vue': {
      routes:
        | '/songs/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
