[package]
name = "aurelia-core"
version = "0.1.0"
edition = "2024"

[lib]
name = "aurelia_core"
crate-type = ["rlib", "cdylib", "staticlib"]

[dependencies]
anyhow = "1.0"
base64 = "0.22"

chrono = { version = "0.4.38", features = ["serde"] }
derive_more = { version = "2.1", features = ["display"] }
dirs = "6.0"
md5 = "0.8"
once_cell = "1.21.3"
postcard = { version = "1.0", features = ["use-std"] }
progenitor-client = "0.11"
rand = "0.9"
redb = "3.1"
reqwest = { version = "0.12", default-features = false, features = [
  "blocking",
  "json",
  "rustls-tls",
  "stream",
] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
specta = { version = "=2.0.0-rc.22", features = ["derive", "function"] }
stream-download = { version = "0.22", features = ["reqwest-rustls"] }
thiserror = "2"
tracing = "0.1"
urlencoding = "2.1"
uuid = { version = "1.19", features = ["v4"] }
tokio = { version = "1.43", features = ["rt-multi-thread"] }
uniffi = { version = "0.31.0", features = ["tokio"] }
