use aurelia_core::error::AppError;
use aurelia_core::listenbrainz_core::{ListenBrainzCredentials, ListenBrainzListen};
use aurelia_core::models::auth::Credentials;
use aurelia_core::models::library::{
    HomeViewData, LastFmCredentials, LibraryData, MobileHomeData, NowPlayingPayload, RpcActivity,
    SyncStateInfo,
};
use aurelia_core::models::lyrics::{ParsedLyrics, ParsedLyricsLine, ParsedLyricsWord};
use aurelia_core::models::music::{
    Album, Artist, NameIdPair, Playlist, PlaylistCreateData, PlaylistUpdateData, Song, UserData,
};
use specta_typescript::{BigIntExportBehavior, Typescript};
use std::fs;
use std::path::Path;

/// Generate TypeScript bindings for Android (uniffi)
/// Generates a single consolidated types file with proper dependencies
pub fn generate_typescript_bindings(out_dir: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let types_dir = out_dir.join("types");
    fs::create_dir_all(&types_dir)?;

    let config = Typescript::new().bigint(BigIntExportBehavior::Number);

    // Generate types in dependency order (base types first)
    let types_in_order: Vec<(&str, String)> = vec![
        // Base types (no dependencies on other custom types)
        (
            "nameIdPair",
            specta_typescript::export::<NameIdPair>(&config)?,
        ),
        ("userData", specta_typescript::export::<UserData>(&config)?),
        (
            "credentials",
            specta_typescript::export::<Credentials>(&config)?,
        ),
        (
            "listenBrainzCredentials",
            specta_typescript::export::<ListenBrainzCredentials>(&config)?,
        ),
        (
            "listenBrainzListen",
            specta_typescript::export::<ListenBrainzListen>(&config)?,
        ),
        // Music types (may depend on base types)
        ("song", specta_typescript::export::<Song>(&config)?),
        ("artist", specta_typescript::export::<Artist>(&config)?),
        ("album", specta_typescript::export::<Album>(&config)?),
        ("playlist", specta_typescript::export::<Playlist>(&config)?),
        (
            "playlistCreateData",
            specta_typescript::export::<PlaylistCreateData>(&config)?,
        ),
        (
            "playlistUpdateData",
            specta_typescript::export::<PlaylistUpdateData>(&config)?,
        ),
        // Library types (depend on music types)
        (
            "libraryData",
            specta_typescript::export::<LibraryData>(&config)?,
        ),
        (
            "homeViewData",
            specta_typescript::export::<HomeViewData>(&config)?,
        ),
        (
            "mobileHomeData",
            specta_typescript::export::<MobileHomeData>(&config)?,
        ),
        (
            "syncStateInfo",
            specta_typescript::export::<SyncStateInfo>(&config)?,
        ),
        (
            "parsedLyricsWord",
            specta_typescript::export::<ParsedLyricsWord>(&config)?,
        ),
        (
            "parsedLyricsLine",
            specta_typescript::export::<ParsedLyricsLine>(&config)?,
        ),
        (
            "parsedLyrics",
            specta_typescript::export::<ParsedLyrics>(&config)?,
        ),
        // Error type
        ("appError", specta_typescript::export::<AppError>(&config)?),
        // Desktop-specific types
        (
            "rpcActivity",
            specta_typescript::export::<RpcActivity>(&config)?,
        ),
        (
            "nowPlayingPayload",
            specta_typescript::export::<NowPlayingPayload>(&config)?,
        ),
        (
            "lastFmCredentials",
            specta_typescript::export::<LastFmCredentials>(&config)?,
        ),
    ];

    // Build a consolidated types file with proper imports
    let mut consolidated_types = String::new();
    consolidated_types.push_str("// Auto-generated TypeScript types for Aurelia\n");
    consolidated_types.push_str("// Generated by uniffi-bindgen - DO NOT EDIT MANUALLY\n\n");

    consolidated_types.push_str(&format!(
        "export const APP_VERSION = '{}';\n\n",
        aurelia_core::utils::constants::APP_VERSION
    ));

    // Track which types we've defined so we can add imports
    let mut defined_types: Vec<&str> = Vec::new();

    for (name, content) in &types_in_order {
        let type_name = to_pascal_case(name);

        // Check if this type references other types that need imports
        let mut imports = Vec::new();
        for defined in &defined_types {
            let defined_pascal = to_pascal_case(defined);
            if content.contains(&defined_pascal) && defined_pascal != type_name {
                imports.push(defined_pascal.to_string());
            }
        }

        if !imports.is_empty() {
            consolidated_types.push_str(&format!(
                "// {} depends on: {}\n",
                type_name,
                imports.join(", ")
            ));
        }

        consolidated_types.push_str(content);
        consolidated_types.push_str("\n\n");

        defined_types.push(name);
    }

    // Write consolidated types file
    let types_filepath = types_dir.join("index.ts");
    fs::write(&types_filepath, consolidated_types)?;

    // Write simple re-export
    let index_content = "export * from './types/index';\n";
    fs::write(out_dir.join("index.ts"), index_content)?;

    println!("Generated TypeScript bindings in {}", out_dir.display());
    Ok(())
}

fn to_pascal_case(s: &str) -> String {
    let mut result = String::new();
    let mut capitalize_next = true;

    for c in s.chars() {
        if c == '_' || c == '-' {
            capitalize_next = true;
        } else if capitalize_next {
            result.push(c.to_ascii_uppercase());
            capitalize_next = false;
        } else {
            result.push(c);
        }
    }

    result
}
