[package]
name = "uniffi-bindgen"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "uniffi-bindgen"
path = "src/main.rs"

[dependencies]
uniffi = { version = "0.31.0", features = ["cli"] }
uniffi_bindgen = "0.31.0"
camino = "1.1.9"
clap = { version = "4", features = ["derive"] }
specta = { version = "=2.0.0-rc.22", features = ["derive", "export"] }
specta-typescript = "0.0.9"
aurelia-core = { path = "../aurelia-core" }
