
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/

export const commands = {
/**
 * Add items to a playlist
 */
  addPlaylistItems: async (playlistId: string, itemIds: string[]): Promise<Result<null, string>> => {
    try {
      return { data: await TAURI_INVOKE('add_playlist_items', { itemIds, playlistId }), status: 'ok' }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { error: e  as any, status: 'error' }
    }
  },
  cacheImageFromUrl: async (itemId: string, imageType: string, imageUrl: string, serverUrl: string, token: string): Promise<Result<string, string>> => {
    try {
      return { data: await TAURI_INVOKE('cache_image_from_url', { imageType, imageUrl, itemId, serverUrl, token }), status: 'ok' }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { error: e  as any, status: 'error' }
    }
  },
  /**
 * Clear the music cache, then re-fetch and cache the library
 */
  clearCache: async (serverUrl: string, token: string): Promise<Result<null, string>> => {
    try {
      return { data: await TAURI_INVOKE('clear_cache', { serverUrl, token }), status: 'ok' }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { error: e  as any, status: 'error' }
    }
  },
  clearImageCache: async (): Promise<Result<null, string>> => {
    try {
      return { data: await TAURI_INVOKE('clear_image_cache'), status: 'ok' }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { error: e  as any, status: 'error' }
    }
  },
  /**
 * Create a new playlist on Jellyfin server
 */
  createPlaylist: async (data: PlaylistCreateData): Promise<Result<Playlist, string>> => {
    try {
      return { data: await TAURI_INVOKE('create_playlist', { data }), status: 'ok' }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { error: e  as any, status: 'error' }
    }
  },
  /**
 * Delete a specific cached image by item ID and type
 */
  deleteCachedImage: async (itemId: string, imageType: string): Promise<Result<null, string>> => {
    try {
      return { data: await TAURI_INVOKE('delete_cached_image', { imageType, itemId }), status: 'ok' }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { error: e  as any, status: 'error' }
    }
  },
  /**
 * Delete a playlist from Jellyfin server
 */
  deletePlaylist: async (playlistId: string): Promise<Result<null, string>> => {
    try {
      return { data: await TAURI_INVOKE('delete_playlist', { playlistId }), status: 'ok' }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { error: e  as any, status: 'error' }
    }
  },
  /**
 * Get single album by ID
 */
  getAlbum: async (albumId: string, includeSongs: boolean | null): Promise<Result<Album, string>> => {
    try {
      return { data: await TAURI_INVOKE('get_album', { albumId, includeSongs }), status: 'ok' }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { error: e  as any, status: 'error' }
    }
  },
  /**
 * Get albums with optional filtering and song inclusion
 */
  getAlbums: async (serverUrl: null | string, token: null | string, includeSongs: boolean | null, limit: null | number, offset: null | number): Promise<Result<Album[], string>> => {
    try {
      return { data: await TAURI_INVOKE('get_albums', { includeSongs, limit, offset, serverUrl, token }), status: 'ok' }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { error: e  as any, status: 'error' }
    }
  },
  /**
 * Get share URLs for an album
 */
  getAlbumShareUrls: async (albumId: string): Promise<Result<Partial<{ [key in string]: string }>, string>> => {
    try {
      return { data: await TAURI_INVOKE('get_album_share_urls', { albumId }), status: 'ok' }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { error: e  as any, status: 'error' }
    }
  },
  /**
 * Get single artist by ID
 */
  getArtist: async (artistId: string, includeSongs: boolean | null, albumArtistsOnly: boolean | null): Promise<Result<Artist, string>> => {
    try {
      return { data: await TAURI_INVOKE('get_artist', { albumArtistsOnly, artistId, includeSongs }), status: 'ok' }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { error: e  as any, status: 'error' }
    }
  },
  /**
 * Get artists with optional filtering and song inclusion
 */
  getArtists: async (serverUrl: null | string, token: null | string, includeSongs: boolean | null, albumArtistsOnly: boolean | null, limit: null | number, offset: null | number): Promise<Result<Artist[], string>> => {
    try {
      return { data: await TAURI_INVOKE('get_artists', { albumArtistsOnly, includeSongs, limit, offset, serverUrl, token }), status: 'ok' }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { error: e  as any, status: 'error' }
    }
  },
  /**
 * Get share URLs for an artist
 */
  getArtistShareUrls: async (artistId: string): Promise<Result<Partial<{ [key in string]: string }>, string>> => {
    try {
      return { data: await TAURI_INVOKE('get_artist_share_urls', { artistId }), status: 'ok' }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { error: e  as any, status: 'error' }
    }
  },
  /**
 * Get audio stream URL
 */
  getAudioStreamUrl: async (serverUrl: string, token: string, itemId: string, container: null | string): Promise<Result<string, string>> => {
    try {
      return { data: await TAURI_INVOKE('get_audio_stream_url', { container, itemId, serverUrl, token }), status: 'ok' }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { error: e  as any, status: 'error' }
    }
  },
  /**
 * Get the current blur mode
 */
  getBlurMode:           async (): Promise<string> => await TAURI_INVOKE('get_blur_mode'),
  getCachedImageDataUrl: async (itemId: string, imageType: string): Promise<Result<null | string, string>> => {
    try {
      return { data: await TAURI_INVOKE('get_cached_image_data_url', { imageType, itemId }), status: 'ok' }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { error: e  as any, status: 'error' }
    }
  },
  getImageCacheStats: async (): Promise<Result<string, string>> => {
    try {
      return { data: await TAURI_INVOKE('get_image_cache_stats'), status: 'ok' }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { error: e  as any, status: 'error' }
    }
  },
  /**
 * Get lyrics for a track
 */
  getLyrics: async (id: string, artist: string, title: string, path: null | string): Promise<Result<string, string>> => {
    try {
      return { data: await TAURI_INVOKE('get_lyrics', { artist, id, path, title }), status: 'ok' }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { error: e  as any, status: 'error' }
    }
  },
  /**
 * Get items in a playlist
 */
  getPlaylistItems: async (playlistId: string): Promise<Result<Song[], string>> => {
    try {
      return { data: await TAURI_INVOKE('get_playlist_items', { playlistId }), status: 'ok' }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { error: e  as any, status: 'error' }
    }
  },
  /**
 * Get all playlists from Jellyfin server
 */
  getPlaylists: async (): Promise<Result<Playlist[], string>> => {
    try {
      return { data: await TAURI_INVOKE('get_playlists'), status: 'ok' }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { error: e  as any, status: 'error' }
    }
  },
  /**
 * Get recently played songs
 */
  getRecentlyPlayed: async (serverUrl: string, token: string): Promise<Result<Song[], string>> => {
    try {
      return { data: await TAURI_INVOKE('get_recently_played', { serverUrl, token }), status: 'ok' }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { error: e  as any, status: 'error' }
    }
  },
  /**
 * Load saved credentials from disk
 */
  getSavedCredentials: async (): Promise<Result<Credentials | null, string>> => {
    try {
      return { data: await TAURI_INVOKE('get_saved_credentials'), status: 'ok' }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { error: e  as any, status: 'error' }
    }
  },
  /**
 * Load saved volume preference
 */
  getSavedVolume: async (): Promise<Result<null | number, string>> => {
    try {
      return { data: await TAURI_INVOKE('get_saved_volume'), status: 'ok' }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { error: e  as any, status: 'error' }
    }
  },
  /**
 * Get single song by ID
 */
  getSong: async (songId: string): Promise<Result<Song, string>> => {
    try {
      return { data: await TAURI_INVOKE('get_song', { songId }), status: 'ok' }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { error: e  as any, status: 'error' }
    }
  },
  /**
 * Get songs with optional filtering
 */
  getSongs: async (serverUrl: null | string, token: null | string, limit: null | number, offset: null | number, albumId: null | string, artistId: null | string): Promise<Result<Song[], string>> => {
    try {
      return { data: await TAURI_INVOKE('get_songs', { albumId, artistId, limit, offset, serverUrl, token }), status: 'ok' }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { error: e  as any, status: 'error' }
    }
  },
  /**
 * Get share URLs for a song
 */
  getSongShareUrls: async (songId: string): Promise<Result<Partial<{ [key in string]: string }>, string>> => {
    try {
      return { data: await TAURI_INVOKE('get_song_share_urls', { songId }), status: 'ok' }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { error: e  as any, status: 'error' }
    }
  },
  hideMainWindow: async (): Promise<void> => {
    await TAURI_INVOKE('hide_main_window')
  },
  /**
 * Login to Jellyfin server
 */
  loginToJellyfin: async (serverUrl: string, username: string, password: string): Promise<Result<LoginResponse, string>> => {
    try {
      return { data: await TAURI_INVOKE('login_to_jellyfin', { password, serverUrl, username }), status: 'ok' }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { error: e  as any, status: 'error' }
    }
  },
  /**
 * Mark item as played in Jellyfin
 */
  markItemPlayed: async (serverUrl: string, token: string, userId: string, itemId: string): Promise<Result<null, string>> => {
    try {
      return { data: await TAURI_INVOKE('mark_item_played', { itemId, serverUrl, token, userId }), status: 'ok' }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { error: e  as any, status: 'error' }
    }
  },
  quitApplication: async (): Promise<void> => {
    await TAURI_INVOKE('quit_application')
  },
  /**
 * Register client capabilities with Jellyfin server
 */
  registerClientCapabilities: async (serverUrl: string, token: string): Promise<Result<null, string>> => {
    try {
      return { data: await TAURI_INVOKE('register_client_capabilities', { serverUrl, token }), status: 'ok' }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { error: e  as any, status: 'error' }
    }
  },
  /**
 * Remove items from a playlist
 */
  removePlaylistItems: async (playlistId: string, itemIds: string[]): Promise<Result<null, string>> => {
    try {
      return { data: await TAURI_INVOKE('remove_playlist_items', { itemIds, playlistId }), status: 'ok' }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { error: e  as any, status: 'error' }
    }
  },
  /**
 * Report playback progress to Jellyfin server
 */
  reportPlaybackProgress: async (serverUrl: string, token: string, itemId: string, positionTicks: null | number, eventName: null | string, isPaused: boolean | null): Promise<Result<null, string>> => {
    try {
      return { data: await TAURI_INVOKE('report_playback_progress', { eventName, isPaused, itemId, positionTicks, serverUrl, token }), status: 'ok' }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { error: e  as any, status: 'error' }
    }
  },
  /**
 * Report playback start to Jellyfin server
 */
  reportPlaybackStart: async (serverUrl: string, token: string, itemId: string, positionTicks: null | number): Promise<Result<null, string>> => {
    try {
      return { data: await TAURI_INVOKE('report_playback_start', { itemId, positionTicks, serverUrl, token }), status: 'ok' }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { error: e  as any, status: 'error' }
    }
  },
  /**
 * Report playback stop to Jellyfin server
 */
  reportPlaybackStop: async (serverUrl: string, token: string, itemId: string, positionTicks: null | number): Promise<Result<null, string>> => {
    try {
      return { data: await TAURI_INVOKE('report_playback_stop', { itemId, positionTicks, serverUrl, token }), status: 'ok' }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { error: e  as any, status: 'error' }
    }
  },
  /**
 * Save user credentials to disk
 */
  saveCredentials: async (serverUrl: string, username: string, token: string, userId: string): Promise<Result<null, string>> => {
    try {
      return { data: await TAURI_INVOKE('save_credentials', { serverUrl, token, userId, username }), status: 'ok' }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { error: e  as any, status: 'error' }
    }
  },
  /**
 * Save user volume preference
 */
  saveVolume: async (volume: number): Promise<Result<null, string>> => {
    try {
      return { data: await TAURI_INVOKE('save_volume', { volume }), status: 'ok' }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { error: e  as any, status: 'error' }
    }
  },
  /**
 * Set the window blur mode
 * On Linux, blur effects are not supported
 * On Windows/macOS, this applies the appropriate vibrancy effect
 */
  setBlurMode: async (mode: string): Promise<Result<null, string>> => {
    try {
      return { data: await TAURI_INVOKE('set_blur_mode', { mode }), status: 'ok' }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { error: e  as any, status: 'error' }
    }
  },
  setCloseToTray: async (closeToTray: boolean): Promise<void> => {
    await TAURI_INVOKE('set_close_to_tray', { closeToTray })
  },
  setMinimizeToTray: async (minimizeToTray: boolean): Promise<void> => {
    await TAURI_INVOKE('set_minimize_to_tray', { minimizeToTray })
  },
  showMainWindow: async (): Promise<void> => {
    await TAURI_INVOKE('show_main_window')
  },
  /**
 * Sync music library - update existing data without clearing cache
 */
  syncLibrary: async (serverUrl: string, token: string): Promise<Result<null, string>> => {
    try {
      return { data: await TAURI_INVOKE('sync_library', { serverUrl, token }), status: 'ok' }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { error: e  as any, status: 'error' }
    }
  },
  /**
 * Toggle favorite status for a track
 */
  toggleFavoriteStatus: async (serverUrl: string, token: string, userId: string, itemId: string, isFavorite: boolean): Promise<Result<boolean, string>> => {
    try {
      return { data: await TAURI_INVOKE('toggle_favorite_status', { isFavorite, itemId, serverUrl, token, userId }), status: 'ok' }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { error: e  as any, status: 'error' }
    }
  },
  /**
 * Update an existing playlist on Jellyfin server
 */
  updatePlaylist: async (playlistId: string, updates: PlaylistUpdateData): Promise<Result<Playlist, string>> => {
    try {
      return { data: await TAURI_INVOKE('update_playlist', { playlistId, updates }), status: 'ok' }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { error: e  as any, status: 'error' }
    }
  },
}

/** user-defined events **/

/** user-defined constants **/

/** user-defined types **/

/**
 * Consolidated album type with all information
 */
export type Album = {
/**
 * URL to album artwork
 */
  albumArtUrl: null | string;
  /**
 * Primary artist name
 */
  artist:      string;
  /**
 * Primary artist ID
 */
  artistId:    null | string;
  /**
 * Date created (when added to server)
 */
  dateCreated: null | string
  /**
 * Album ID from Jellyfin
 */
  id:          null | string;
  /**
 * Image tags
 */
  imageTags:   null | Partial<{ [key in string]: string }>;
  /**
 * Album name
 */
  name:        string;
  /**
 * External provider IDs (`MusicBrainz`, etc.)
 */
  providerIds: null | Partial<{ [key in string]: string }>;
  /**
 * Number of songs in album
 */
  songCount:   bigint;
  /**
 * Optional list of songs in this album (only populated when needed)
 */
  songs:       null | Song[]; }
/**
 * Consolidated artist type with all information
 */
export type Artist = {
/**
 * Community rating
 */
  communityRating: null | number;
  /**
 * Artist ID
 */
  id:              string;
  /**
 * Image tags (metadata about available images)
 */
  imageTags:       null | Partial<{ [key in string]: string }>;
  /**
 * URL to artist image
 */
  imageUrl:        null | string;
  /**
 * Artist name
 */
  name:            string;
  /**
 * Artist biography/description
 */
  overview:        null | string;
  /**
 * External provider IDs (`MusicBrainz`, etc.)
 */
  providerIds:     null | Partial<{ [key in string]: string }>;
  /**
 * Number of songs by this artist
 */
  songCount:       bigint | null;
  /**
 * Optional list of songs by this artist (only populated when needed)
 */
  songs:           null | Song[] }
/**
 * User credentials for Jellyfin authentication
 */
export type Credentials = {
/**
 * Jellyfin server URL
 */
  serverUrl: string;
  /**
 * Authentication token
 */
  token:     string;
  /**
 * User ID
 */
  userId:    string
  /**
 * Username
 */
  username:  string; }
/**
 * Response from successful Jellyfin login
 */
export type LoginResponse = {
/**
 * User authentication token
 */
  token:  string;
  /**
 * User ID
 */
  userId: string }
/**
 * Generic name-ID pair used for artists and other entities
 */
export type NameIdPair = {
/**
 * Unique identifier
 */
  id:   string
  /**
 * Display name
 */
  name: string; }
/**
 * Playlist representing a collection of items
 */
export type Playlist = {
/**
 * Backdrop image tags
 */
  backdropImageTags: null | string[];
  /**
 * Whether playlist can be deleted
 */
  canDelete:         boolean | null;
  /**
 * Child count (number of items in playlist)
 */
  childCount:        null | number;
  /**
 * Date created
 */
  dateCreated:       null | string;
  /**
 * Date last modified
 */
  dateLastSaved:     null | string;
  /**
 * Playlist description
 */
  description:       null | string;
  /**
 * Playlist ID
 */
  id:                string;
  /**
 * Image blur hashes
 */
  imageBlurHashes:   null | Partial<{ [key in string]: Partial<{ [key in string]: string }> }>;
  /**
 * Image tags
 */
  imageTags:         null | Partial<{ [key in string]: string }>;
  /**
 * Whether playlist is favorited
 */
  isFavorite:        boolean | null;
  /**
 * Whether this is a folder (playlists are folders containing items)
 */
  isFolder:          boolean;
  /**
 * Item type (should be "Playlist")
 */
  itemType:          string;
  /**
 * Location type
 */
  locationType:      string;
  /**
 * Media type
 */
  mediaType:         null | string;
  /**
 * Playlist name
 */
  name:              string;
  /**
 * Runtime ticks (total duration)
 */
  runTimeTicks:      bigint | null;
  /**
 * Server ID
 */
  serverId:          string;
  /**
 * Songs in the playlist
 */
  songs:             null | Song[]
  /**
 * Sort name
 */
  sortName:          null | string;
  /**
 * User data
 */
  userData:          null | UserData; }
/**
 * Data for creating a new playlist
 */
export type PlaylistCreateData = {
/**
 * Item IDs to include in the playlist
 */
  ids:      null | string[];
  /**
 * Whether playlist is public
 */
  isPublic: boolean | null
  /**
 * Playlist name
 */
  name:     string;
  /**
 * User ID creating the playlist
 */
  userId:   string; }
/**
 * Data for updating a playlist
 */
export type PlaylistUpdateData = {
/**
 * Item IDs to set for the playlist
 */
  ids:        null | string[];
  /**
 * Whether playlist is favorited
 */
  isFavorite: boolean | null
  /**
 * Whether playlist is public
 */
  isPublic:   boolean | null;
  /**
 * New playlist name
 */
  name:       null | string;
  /**
 * Songs to set for the playlist
 */
  songs:      null | Song[];
  /**
 * User ID updating the playlist
 */
  userId:     null | string; }
export type Result<T, E> =
	| { data: T; status: 'ok'; }
	| { error: E; status: 'error'; }
/**
 * Song representing a music track or audio file
 */
export type Song = {
/**
 * Album name
 */
  album:        null | string;
  /**
 * Album artists (different from track artists)
 */
  albumArtists: NameIdPair[] | null;
  /**
 * URL to album artwork
 */
  albumArtUrl:  null | string;
  /**
 * Album ID
 */
  albumId:      null | string;
  /**
 * List of artist IDs corresponding to artists
 */
  artistIds:    null | string[];
  /**
 * List of artist names
 */
  artists:      null | string[];
  /**
 * Audio bitrate
 */
  bitRate:      null | number;
  /**
 * Audio codec
 */
  codec:        null | string;
  /**
 * Audio container/format
 */
  container:    null | string;
  /**
 * Date created (when added to server)
 */
  dateCreated:  null | string;
  /**
 * Last played date
 */
  datePlayed:   null | string;
  /**
 * Duration in seconds
 */
  duration:     null | number;
  /**
 * Music genres
 */
  genres:       null | string[];
  /**
 * Unique identifier
 */
  id:           string;
  /**
 * Image tags
 */
  imageTags:    null | Partial<{ [key in string]: string }>
  /**
 * Whether this item is marked as favorite
 */
  isFavorite:   boolean | null;
  /**
 * Type of item (usually "Audio")
 */
  itemType:     string;
  /**
 * Song lyrics
 */
  lyrics:       null | string;
  /**
 * Song title
 */
  name:         string;
  /**
 * File path
 */
  path:         null | string;
  /**
 * Number of times played
 */
  playCount:    null | number;
  /**
 * Premiere/release date
 */
  premiereDate: null | string;
  /**
 * Audio sample rate
 */
  sampleRate:   null | number;
  /**
 * Track number in album
 */
  trackNumber:  null | number;
  /**
 * Release year
 */
  year:         null | number; }

/** tauri-specta globals **/

import {
  Channel as TAURI_CHANNEL,
  invoke as TAURI_INVOKE,
} from '@tauri-apps/api/core'
import * as TAURI_API_EVENT from '@tauri-apps/api/event'
import { type WebviewWindow as __WebviewWindow__ } from '@tauri-apps/api/webviewWindow'

/**
 * User data for items (play count, favorites, etc.)
 */
export type UserData = { isFavorite: boolean; lastPlayedDate: null | string; playbackPositionTicks: bigint; playCount: number; played: boolean; }

type __EventObj__<T> = {
  emit: null extends T
    ? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
    : (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
  listen: (
    cb: TAURI_API_EVENT.EventCallback<T>,
  ) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
  once: (
    cb: TAURI_API_EVENT.EventCallback<T>,
  ) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
}

const __makeEvents__ = <T extends Record<string, any>>(mappings: Record<keyof T, string>) => new Proxy(
  {} as unknown as {
    [K in keyof T]: __EventObj__<T[K]> & {
      (handle: __WebviewWindow__): __EventObj__<T[K]>;
    };
  },
  {
    get: (_, event) => {
      const name = mappings[event as keyof T]

      return new Proxy((() => {}) as any, {
        apply: (_, __, [window]: [__WebviewWindow__]) => ({
          emit:   (arg: any) => window.emit(name, arg),
          listen: (arg: any) => window.listen(name, arg),
          once:   (arg: any) => window.once(name, arg),
        }),
        get: (_, command: keyof __EventObj__<any>) => {
          switch (command) {
            case 'emit':
              return (arg: any) => TAURI_API_EVENT.emit(name, arg)
            case 'listen':
              return (arg: any) => TAURI_API_EVENT.listen(name, arg)
            case 'once':
              return (arg: any) => TAURI_API_EVENT.once(name, arg)
          }
        },
      })
    },
  },
)
